// Generated by msgbuilder 2020-05-13 09:44:06 +0000

import StdMsgs
import msgs

enum custom_msgs {}

extension custom_msgs {
	public enum AddTwoInts: ServiceProt {
		public static let md5sum: String = "6a2e34150c00229791cc89ff309fff21"
		public static let datatype = "custom_msgs/AddTwoInts"


		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "36d09b846be0b371c5f190354dd3153e"
			public static let datatype = "custom_msgs/AddTwoIntsRequest"
			public typealias ServiceType = AddTwoInts
			public static let definition = """
				int64 a
				int64 b
				"""
	
		
			public var a: Int64
			public var b: Int64
	
			public init(a: Int64, b: Int64) {
				self.a = a
				self.b = b
			}
	
			public init() {
				a = Int64()
				b = Int64()
			}
		}


		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "b88405221c77b1878a3cbbfff53428d7"
			public static let datatype = "custom_msgs/AddTwoIntsResponse"
			public typealias ServiceType = AddTwoInts
			public static let definition = """
				int64 sum
				"""
	
		
			public var sum: Int64
	
			public init(sum: Int64) {
				self.sum = sum
			}
	
			public init() {
				sum = Int64()
			}
		}

	}
}
