// Generated by msgbuilder 2020-05-10 06:44:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct ApplyJointEffort: ServiceProt {
		public typealias Request = gazebo_msgs.ApplyJointEffortRequest
		public typealias Response = gazebo_msgs.ApplyJointEffortResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "c0039811b8cc919490b3cff748cdf46b"
		public static let datatype = "gazebo_msgs/ApplyJointEffort"
	}
}