// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct ApplyBodyWrench: ServiceProt {
		public typealias Request = ApplyBodyWrenchRequest
		public typealias Response = ApplyBodyWrenchResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "585b9f9618aa0581b207e2f2d90866bc"
		public static let datatype = "gazebo_msgs/ApplyBodyWrench"
	}
}