// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension gazebo_msgs {

	public struct BodyRequestRequest: ServiceMessage {
		public static let md5sum: String = "5eade9afe7f232d78005bd0cafeab755"
		public static let datatype = "gazebo_msgs/BodyRequestRequest"
		public static var srvMd5sum: String = BodyRequest.md5sum
		public static var srvDatatype: String = BodyRequest.datatype
		public static let definition = """
			string body_name   # name of the body requested. body names are prefixed by model name, e.g. pr2::base_link
			"""

	
		public var body_name: String

		public init(body_name: String) {
			self.body_name = body_name
		}

		public init() {
			body_name = String()
		}
	}
}