// Generated by msgbuilder 2020-05-14 06:44:12 +0000

import StdMsgs

extension gazebo_msgs {
	public enum BodyRequest: ServiceProt {
		public static let md5sum: String = "5eade9afe7f232d78005bd0cafeab755"
		public static let datatype = "gazebo_msgs/BodyRequest"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "5eade9afe7f232d78005bd0cafeab755"
			public static let datatype = "gazebo_msgs/BodyRequestRequest"
			public typealias ServiceType = BodyRequest
			public static let definition = """
				string body_name   # name of the body requested. body names are prefixed by model name, e.g. pr2::base_link
				"""
	
		
			public var body_name: String
	
			public init(body_name: String) {
				self.body_name = body_name
			}
	
			public init() {
				body_name = String()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
			public static let datatype = "gazebo_msgs/BodyRequestResponse"
			public typealias ServiceType = BodyRequest
			public static let definition = """
				
				"""
	
		
		
	
	
	
			public init() {
		
			}
		}

	}
}