// Generated by msgbuilder 2020-05-10 05:59:00 +0000

import StdMsgs

extension gazebo_msgs {
	public struct BodyRequest: ServiceProt {
		public typealias Request = gazebo_msgs.BodyRequestRequest
		public typealias Response = gazebo_msgs.BodyRequestResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "5eade9afe7f232d78005bd0cafeab755"
		public static let datatype = "gazebo_msgs/BodyRequest"
	}
}