// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct BodyRequest: ServiceProt {
		public typealias Request = BodyRequestRequest
		public typealias Response = BodyRequestResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "5eade9afe7f232d78005bd0cafeab755"
		public static let datatype = "gazebo_msgs/BodyRequest"
	}
}