// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct DeleteLight: ServiceProt {
		public typealias Request = DeleteLightRequest
		public typealias Response = DeleteLightResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "ae11ea8100d536d5b92c2b5917abf912"
		public static let datatype = "gazebo_msgs/DeleteLight"
	}
}