// Generated by msgbuilder 2020-05-10 06:44:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct DeleteModel: ServiceProt {
		public typealias Request = gazebo_msgs.DeleteModelRequest
		public typealias Response = gazebo_msgs.DeleteModelResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "9ce56b4e9e54616de25d796dc972a262"
		public static let datatype = "gazebo_msgs/DeleteModel"
	}
}