// Generated by msgbuilder 2020-05-15 06:20:49 +0000

import StdMsgs

extension gazebo_msgs {
	public enum DeleteLight: ServiceProt {
		public static let md5sum: String = "ae11ea8100d536d5b92c2b5917abf912"
		public static let datatype = "gazebo_msgs/DeleteLight"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "4fb676dfb4741fc866365702a859441c"
			public static let datatype = "gazebo_msgs/DeleteLightRequest"
			public typealias ServiceType = DeleteLight
			public static let definition = """
				string light_name                 # name of the light to be deleted
				"""
	
			public var light_name: String
	
			public init(light_name: String) {
				self.light_name = light_name
			}
	
			public init() {
				light_name = String()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "2ec6f3eff0161f4257b808b12bc830c2"
			public static let datatype = "gazebo_msgs/DeleteLightResponse"
			public typealias ServiceType = DeleteLight
			public static let definition = """
				bool success                      # return true if deletion is successful
				string status_message             # comments if available
				"""
	
			public var success: Bool
			public var status_message: String
	
			public init(success: Bool, status_message: String) {
				self.success = success
				self.status_message = status_message
			}
	
			public init() {
				success = Bool()
				status_message = String()
			}
		}

	}
}