// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension gazebo_msgs {

	public struct DeleteLightRequest: ServiceMessage {
		public static let md5sum: String = "4fb676dfb4741fc866365702a859441c"
		public static let datatype = "gazebo_msgs/DeleteLightRequest"
		public static var srvMd5sum: String = DeleteLight.md5sum
		public static var srvDatatype: String = DeleteLight.datatype
		public static let definition = """
			string light_name                 # name of the light to be deleted
			"""

	
		public var light_name: String

		public init(light_name: String) {
			self.light_name = light_name
		}

		public init() {
			light_name = String()
		}
	}
}