// Generated by msgbuilder 2020-05-14 06:44:12 +0000

import StdMsgs

extension gazebo_msgs {
	public enum DeleteModel: ServiceProt {
		public static let md5sum: String = "9ce56b4e9e54616de25d796dc972a262"
		public static let datatype = "gazebo_msgs/DeleteModel"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "ea31c8eab6fc401383cf528a7c0984ba"
			public static let datatype = "gazebo_msgs/DeleteModelRequest"
			public typealias ServiceType = DeleteModel
			public static let definition = """
				string model_name                 # name of the Gazebo Model to be deleted
				"""
	
		
			public var model_name: String
	
			public init(model_name: String) {
				self.model_name = model_name
			}
	
			public init() {
				model_name = String()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "2ec6f3eff0161f4257b808b12bc830c2"
			public static let datatype = "gazebo_msgs/DeleteModelResponse"
			public typealias ServiceType = DeleteModel
			public static let definition = """
				bool success                      # return true if deletion is successful
				string status_message             # comments if available
				"""
	
		
			public var success: Bool
			public var status_message: String
	
			public init(success: Bool, status_message: String) {
				self.success = success
				self.status_message = status_message
			}
	
			public init() {
				success = Bool()
				status_message = String()
			}
		}

	}
}