// Generated by msgbuilder 2020-05-10 06:44:09 +0000

import StdMsgs

extension gazebo_msgs {
	public struct DeleteLight: ServiceProt {
		public typealias Request = gazebo_msgs.DeleteLightRequest
		public typealias Response = gazebo_msgs.DeleteLightResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "ae11ea8100d536d5b92c2b5917abf912"
		public static let datatype = "gazebo_msgs/DeleteLight"
	}
}