// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

public enum gazebo_msgs {
    public static let all: [String: Message.Type] = [
        "ContactState": ContactState.self,
		"ContactsState": ContactsState.self,
		"LinkState": LinkState.self,
		"LinkStates": LinkStates.self,
		"ModelState": ModelState.self,
		"ModelStates": ModelStates.self,
		"ODEJointProperties": ODEJointProperties.self,
		"ODEPhysics": ODEPhysics.self,
		"WorldState": WorldState.self]
}