// Generated by msgbuilder 2020-05-10 10:59:44 +0000

import StdMsgs

public enum gazebo_msgs {
    public static let all: [String: Message.Type] = [
        "WorldState": WorldState.self,
		"ContactsState": ContactsState.self,
		"ODEPhysics": ODEPhysics.self,
		"ModelStates": ModelStates.self,
		"LinkState": LinkState.self,
		"LinkStates": LinkStates.self,
		"ModelState": ModelState.self,
		"ContactState": ContactState.self,
		"ODEJointProperties": ODEJointProperties.self]
}