// Generated by msgbuilder 2020-05-10 06:44:09 +0000

import StdMsgs

extension gazebo_msgs {
	public struct GetJointProperties: ServiceProt {
		public typealias Request = gazebo_msgs.GetJointPropertiesRequest
		public typealias Response = gazebo_msgs.GetJointPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "0b15ad073ec115b3e511a647643119a4"
		public static let datatype = "gazebo_msgs/GetJointProperties"
	}
}