// Generated by msgbuilder 2020-05-10 06:44:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct GetLinkProperties: ServiceProt {
		public typealias Request = gazebo_msgs.GetLinkPropertiesRequest
		public typealias Response = gazebo_msgs.GetLinkPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "0e06a70386d0ee3fb880c02f23fcd821"
		public static let datatype = "gazebo_msgs/GetLinkProperties"
	}
}