// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension gazebo_msgs {

	public struct GetLinkPropertiesRequest: ServiceMessage {
		public static let md5sum: String = "7d82d60381f1b66a30f2157f60884345"
		public static let datatype = "gazebo_msgs/GetLinkPropertiesRequest"
		public static var srvMd5sum: String = GetLinkProperties.md5sum
		public static var srvDatatype: String = GetLinkProperties.datatype
		public static let definition = """
			string link_name          # name of link
			                          # link names are prefixed by model name, e.g. pr2::base_link
			"""

	
		public var link_name: String

		public init(link_name: String) {
			self.link_name = link_name
		}

		public init() {
			link_name = String()
		}
	}
}