// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct GetLinkState: ServiceProt {
		public typealias Request = GetLinkStateRequest
		public typealias Response = GetLinkStateResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "09d6c98cce97b35f7ab9bd70300657ab"
		public static let datatype = "gazebo_msgs/GetLinkState"
	}
}