// Generated by msgbuilder 2020-05-14 06:44:12 +0000

import StdMsgs

extension gazebo_msgs {
	public enum GetLinkProperties: ServiceProt {
		public static let md5sum: String = "0e06a70386d0ee3fb880c02f23fcd821"
		public static let datatype = "gazebo_msgs/GetLinkProperties"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "7d82d60381f1b66a30f2157f60884345"
			public static let datatype = "gazebo_msgs/GetLinkPropertiesRequest"
			public typealias ServiceType = GetLinkProperties
			public static let definition = """
				string link_name          # name of link
				                          # link names are prefixed by model name, e.g. pr2::base_link
				"""
	
		
			public var link_name: String
	
			public init(link_name: String) {
				self.link_name = link_name
			}
	
			public init() {
				link_name = String()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "a8619f92d17cfcc3958c0fd13299443d"
			public static let datatype = "gazebo_msgs/GetLinkPropertiesResponse"
			public typealias ServiceType = GetLinkProperties
			public static let definition = """
				geometry_msgs/Pose com    # center of mass location in link frame
				                          # and orientation of the moment of inertias
				                          # relative to the link frame
				bool gravity_mode         # set gravity mode on/off
				float64 mass              # linear mass of link
				float64 ixx               # moment of inertia
				float64 ixy               # moment of inertia
				float64 ixz               # moment of inertia
				float64 iyy               # moment of inertia
				float64 iyz               # moment of inertia
				float64 izz               # moment of inertia
				bool success              # return true if get info is successful
				string status_message     # comments if available
				"""
	
		
			public var com: geometry_msgs.Pose
			public var gravity_mode: Bool
			public var mass: Float64
			public var ixx: Float64
			public var ixy: Float64
			public var ixz: Float64
			public var iyy: Float64
			public var iyz: Float64
			public var izz: Float64
			public var success: Bool
			public var status_message: String
	
			public init(com: geometry_msgs.Pose, gravity_mode: Bool, mass: Float64, ixx: Float64, ixy: Float64, ixz: Float64, iyy: Float64, iyz: Float64, izz: Float64, success: Bool, status_message: String) {
				self.com = com
				self.gravity_mode = gravity_mode
				self.mass = mass
				self.ixx = ixx
				self.ixy = ixy
				self.ixz = ixz
				self.iyy = iyy
				self.iyz = iyz
				self.izz = izz
				self.success = success
				self.status_message = status_message
			}
	
			public init() {
				com = geometry_msgs.Pose()
				gravity_mode = Bool()
				mass = Float64()
				ixx = Float64()
				ixy = Float64()
				ixz = Float64()
				iyy = Float64()
				iyz = Float64()
				izz = Float64()
				success = Bool()
				status_message = String()
			}
		}

	}
}