// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension gazebo_msgs {

	public struct GetLinkStateResponse: ServiceMessage {
		public static let md5sum: String = "8ba55ad34f9c072e75c0de57b089753b"
		public static let datatype = "gazebo_msgs/GetLinkStateResponse"
		public static var srvMd5sum: String = GetLinkState.md5sum
		public static var srvDatatype: String = GetLinkState.datatype
		public static let definition = """
			gazebo_msgs/LinkState link_state
			bool success              # return true if get info is successful
			string status_message     # comments if available
			"""

	
		public var link_state: LinkState
		public var success: Bool
		public var status_message: String

		public init(link_state: LinkState, success: Bool, status_message: String) {
			self.link_state = link_state
			self.success = success
			self.status_message = status_message
		}

		public init() {
			link_state = LinkState()
			success = Bool()
			status_message = String()
		}
	}
}