// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct GetLightProperties: ServiceProt {
		public typealias Request = GetLightPropertiesRequest
		public typealias Response = GetLightPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "df2cef87e13e2e6990e81e8aaa454c19"
		public static let datatype = "gazebo_msgs/GetLightProperties"
	}
}