// Generated by msgbuilder 2020-05-15 06:20:49 +0000

import StdMsgs

extension gazebo_msgs {
	public enum GetLightProperties: ServiceProt {
		public static let md5sum: String = "df2cef87e13e2e6990e81e8aaa454c19"
		public static let datatype = "gazebo_msgs/GetLightProperties"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "4fb676dfb4741fc866365702a859441c"
			public static let datatype = "gazebo_msgs/GetLightPropertiesRequest"
			public typealias ServiceType = GetLightProperties
			public static let definition = """
				string light_name                    # name of Gazebo Light
				"""
	
			public var light_name: String
	
			public init(light_name: String) {
				self.light_name = light_name
			}
	
			public init() {
				light_name = String()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "9a19ddd5aab4c13b7643d1722c709f1f"
			public static let datatype = "gazebo_msgs/GetLightPropertiesResponse"
			public typealias ServiceType = GetLightProperties
			public static let definition = """
				std_msgs/ColorRGBA diffuse           # diffuse color as red, green, blue, alpha
				float64 attenuation_constant
				float64 attenuation_linear
				float64 attenuation_quadratic
				bool success                         # return true if get successful
				string status_message                # comments if available
				"""
	
			public var diffuse: std_msgs.ColorRGBA
			public var attenuation_constant: Float64
			public var attenuation_linear: Float64
			public var attenuation_quadratic: Float64
			public var success: Bool
			public var status_message: String
	
			public init(diffuse: std_msgs.ColorRGBA, attenuation_constant: Float64, attenuation_linear: Float64, attenuation_quadratic: Float64, success: Bool, status_message: String) {
				self.diffuse = diffuse
				self.attenuation_constant = attenuation_constant
				self.attenuation_linear = attenuation_linear
				self.attenuation_quadratic = attenuation_quadratic
				self.success = success
				self.status_message = status_message
			}
	
			public init() {
				diffuse = std_msgs.ColorRGBA()
				attenuation_constant = Float64()
				attenuation_linear = Float64()
				attenuation_quadratic = Float64()
				success = Bool()
				status_message = String()
			}
		}

	}
}