// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct GetLinkProperties: ServiceProt {
		public typealias Request = GetLinkPropertiesRequest
		public typealias Response = GetLinkPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "0e06a70386d0ee3fb880c02f23fcd821"
		public static let datatype = "gazebo_msgs/GetLinkProperties"
	}
}