// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct GetModelState: ServiceProt {
		public typealias Request = GetModelStateRequest
		public typealias Response = GetModelStateResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "4c515e936d3319c9610c559c60bfc3d4"
		public static let datatype = "gazebo_msgs/GetModelState"
	}
}