// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct GetModelProperties: ServiceProt {
		public typealias Request = GetModelPropertiesRequest
		public typealias Response = GetModelPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "5717f7bd34ed990fa80e28b3015027a3"
		public static let datatype = "gazebo_msgs/GetModelProperties"
	}
}