// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension gazebo_msgs {

	public struct GetModelPropertiesResponse: ServiceMessage {
		public static let md5sum: String = "b7f370938ef77b464b95f1bab3ec5028"
		public static let datatype = "gazebo_msgs/GetModelPropertiesResponse"
		public static var srvMd5sum: String = GetModelProperties.md5sum
		public static var srvDatatype: String = GetModelProperties.datatype
		public static let definition = """
			string parent_model_name             # parent model
			string canonical_body_name           # name of canonical body, body names are prefixed by model name, e.g. pr2::base_link
			string[] body_names                  # list of bodies, body names are prefixed by model name, e.g. pr2::base_link
			string[] geom_names                  # list of geoms
			string[] joint_names                 # list of joints attached to the model
			string[] child_model_names           # list of child models
			bool is_static                       # returns true if model is static
			bool success                         # return true if get successful
			string status_message                # comments if available
			"""

	
		public var parent_model_name: String
		public var canonical_body_name: String
		public var body_names: [String]
		public var geom_names: [String]
		public var joint_names: [String]
		public var child_model_names: [String]
		public var is_static: Bool
		public var success: Bool
		public var status_message: String

		public init(parent_model_name: String, canonical_body_name: String, body_names: [String], geom_names: [String], joint_names: [String], child_model_names: [String], is_static: Bool, success: Bool, status_message: String) {
			self.parent_model_name = parent_model_name
			self.canonical_body_name = canonical_body_name
			self.body_names = body_names
			self.geom_names = geom_names
			self.joint_names = joint_names
			self.child_model_names = child_model_names
			self.is_static = is_static
			self.success = success
			self.status_message = status_message
		}

		public init() {
			parent_model_name = String()
			canonical_body_name = String()
			body_names = [String]()
			geom_names = [String]()
			joint_names = [String]()
			child_model_names = [String]()
			is_static = Bool()
			success = Bool()
			status_message = String()
		}
	}
}