// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension gazebo_msgs {

	public struct GetModelPropertiesRequest: ServiceMessage {
		public static let md5sum: String = "ea31c8eab6fc401383cf528a7c0984ba"
		public static let datatype = "gazebo_msgs/GetModelPropertiesRequest"
		public static var srvMd5sum: String = GetModelProperties.md5sum
		public static var srvDatatype: String = GetModelProperties.datatype
		public static let definition = """
			string model_name                    # name of Gazebo Model
			"""

	
		public var model_name: String

		public init(model_name: String) {
			self.model_name = model_name
		}

		public init() {
			model_name = String()
		}
	}
}