// Generated by msgbuilder 2020-05-10 05:59:00 +0000

import StdMsgs

extension gazebo_msgs {
	public struct GetPhysicsProperties: ServiceProt {
		public typealias Request = gazebo_msgs.GetPhysicsPropertiesRequest
		public typealias Response = gazebo_msgs.GetPhysicsPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "575a5e74786981b7df2e3afc567693a6"
		public static let datatype = "gazebo_msgs/GetPhysicsProperties"
	}
}