// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct GetWorldProperties: ServiceProt {
		public typealias Request = GetWorldPropertiesRequest
		public typealias Response = GetWorldPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "36bb0f2eccf4d8be971410c22818ba3f"
		public static let datatype = "gazebo_msgs/GetWorldProperties"
	}
}