// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension gazebo_msgs {

	public struct GetWorldPropertiesRequest: ServiceMessage {
		public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
		public static let datatype = "gazebo_msgs/GetWorldPropertiesRequest"
		public static var srvMd5sum: String = GetWorldProperties.md5sum
		public static var srvDatatype: String = GetWorldProperties.datatype
		public static let definition = """
			
			"""

	
	



		public init() {
	
		}
	}
}