// Generated by msgbuilder 2020-05-14 06:44:12 +0000

import StdMsgs

extension gazebo_msgs {
	public enum JointRequest: ServiceProt {
		public static let md5sum: String = "0be1351618e1dc030eb7959d9a4902de"
		public static let datatype = "gazebo_msgs/JointRequest"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "0be1351618e1dc030eb7959d9a4902de"
			public static let datatype = "gazebo_msgs/JointRequestRequest"
			public typealias ServiceType = JointRequest
			public static let definition = """
				string joint_name   # name of the joint requested
				"""
	
		
			public var joint_name: String
	
			public init(joint_name: String) {
				self.joint_name = joint_name
			}
	
			public init() {
				joint_name = String()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
			public static let datatype = "gazebo_msgs/JointRequestResponse"
			public typealias ServiceType = JointRequest
			public static let definition = """
				
				"""
	
		
		
	
	
	
			public init() {
		
			}
		}

	}
}