// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension gazebo_msgs {

	public struct JointRequestRequest: ServiceMessage {
		public static let md5sum: String = "0be1351618e1dc030eb7959d9a4902de"
		public static let datatype = "gazebo_msgs/JointRequestRequest"
		public static var srvMd5sum: String = JointRequest.md5sum
		public static var srvDatatype: String = JointRequest.datatype
		public static let definition = """
			string joint_name   # name of the joint requested
			"""

	
		public var joint_name: String

		public init(joint_name: String) {
			self.joint_name = joint_name
		}

		public init() {
			joint_name = String()
		}
	}
}