// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct JointRequest: ServiceProt {
		public typealias Request = JointRequestRequest
		public typealias Response = JointRequestResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "0be1351618e1dc030eb7959d9a4902de"
		public static let datatype = "gazebo_msgs/JointRequest"
	}
}