// Generated by msgbuilder 2020-05-10 05:59:01 +0000

import StdMsgs

extension gazebo_msgs {
	public struct JointRequest: ServiceProt {
		public typealias Request = gazebo_msgs.JointRequestRequest
		public typealias Response = gazebo_msgs.JointRequestResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "0be1351618e1dc030eb7959d9a4902de"
		public static let datatype = "gazebo_msgs/JointRequest"
	}
}