// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct SetJointProperties: ServiceProt {
		public typealias Request = SetJointPropertiesRequest
		public typealias Response = SetJointPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "15a76e921b1410c698d82782ea5fa370"
		public static let datatype = "gazebo_msgs/SetJointProperties"
	}
}