// Generated by msgbuilder 2020-05-14 06:44:12 +0000

import StdMsgs

extension gazebo_msgs {
	public enum SetJointProperties: ServiceProt {
		public static let md5sum: String = "15a76e921b1410c698d82782ea5fa370"
		public static let datatype = "gazebo_msgs/SetJointProperties"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "331fd8f35fd27e3c1421175590258e26"
			public static let datatype = "gazebo_msgs/SetJointPropertiesRequest"
			public typealias ServiceType = SetJointProperties
			public static let definition = """
				string joint_name                               # name of joint
				gazebo_msgs/ODEJointProperties ode_joint_config # access to ODE joint dynamics properties
				"""
	
		
			public var joint_name: String
			public var ode_joint_config: ODEJointProperties
	
			public init(joint_name: String, ode_joint_config: ODEJointProperties) {
				self.joint_name = joint_name
				self.ode_joint_config = ode_joint_config
			}
	
			public init() {
				joint_name = String()
				ode_joint_config = ODEJointProperties()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "2ec6f3eff0161f4257b808b12bc830c2"
			public static let datatype = "gazebo_msgs/SetJointPropertiesResponse"
			public typealias ServiceType = SetJointProperties
			public static let definition = """
				bool success                                    # return true if get successful
				string status_message                           # comments if available
				"""
	
		
			public var success: Bool
			public var status_message: String
	
			public init(success: Bool, status_message: String) {
				self.success = success
				self.status_message = status_message
			}
	
			public init() {
				success = Bool()
				status_message = String()
			}
		}

	}
}