// Generated by msgbuilder 2020-05-10 10:56:43 +0000

import StdMsgs

extension gazebo_msgs {

	public struct SetJointTrajectoryRequest: ServiceMessage {
		public static let md5sum: String = "649dd2eba5ffd358069238825f9f85ab"
		public static let datatype = "gazebo_msgs/SetJointTrajectoryRequest"
		public static var srvMd5sum: String = SetJointTrajectory.md5sum
		public static var srvDatatype: String = SetJointTrajectory.datatype
		public static let definition = """
			string model_name
			trajectory_msgs/JointTrajectory joint_trajectory
			geometry_msgs/Pose model_pose
			bool set_model_pose
			bool disable_physics_updates # defaults to false
			"""

	
		public var model_name: String
		public var joint_trajectory: trajectory_msgs.JointTrajectory
		public var model_pose: geometry_msgs.Pose
		public var set_model_pose: Bool
		public var disable_physics_updates: Bool

		public init(model_name: String, joint_trajectory: trajectory_msgs.JointTrajectory, model_pose: geometry_msgs.Pose, set_model_pose: Bool, disable_physics_updates: Bool) {
			self.model_name = model_name
			self.joint_trajectory = joint_trajectory
			self.model_pose = model_pose
			self.set_model_pose = set_model_pose
			self.disable_physics_updates = disable_physics_updates
		}

		public init() {
			model_name = String()
			joint_trajectory = trajectory_msgs.JointTrajectory()
			model_pose = geometry_msgs.Pose()
			set_model_pose = Bool()
			disable_physics_updates = Bool()
		}
	}
}