// Generated by msgbuilder 2020-05-10 06:44:09 +0000

import StdMsgs

extension gazebo_msgs {
	public struct SetJointTrajectory: ServiceProt {
		public typealias Request = gazebo_msgs.SetJointTrajectoryRequest
		public typealias Response = gazebo_msgs.SetJointTrajectoryResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "88f5c10979e3f9649d5ae87a3b12aa65"
		public static let datatype = "gazebo_msgs/SetJointTrajectory"
	}
}