// Generated by msgbuilder 2020-05-10 06:44:09 +0000

import StdMsgs

extension gazebo_msgs {
	public struct SetJointProperties: ServiceProt {
		public typealias Request = gazebo_msgs.SetJointPropertiesRequest
		public typealias Response = gazebo_msgs.SetJointPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "15a76e921b1410c698d82782ea5fa370"
		public static let datatype = "gazebo_msgs/SetJointProperties"
	}
}