// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension gazebo_msgs {

	public struct SetLinkPropertiesResponse: ServiceMessage {
		public static let md5sum: String = "2ec6f3eff0161f4257b808b12bc830c2"
		public static let datatype = "gazebo_msgs/SetLinkPropertiesResponse"
		public static var srvMd5sum: String = SetLinkProperties.md5sum
		public static var srvDatatype: String = SetLinkProperties.datatype
		public static let definition = """
			bool success              # return true if get info is successful
			string status_message     # comments if available
			"""

	
		public var success: Bool
		public var status_message: String

		public init(success: Bool, status_message: String) {
			self.success = success
			self.status_message = status_message
		}

		public init() {
			success = Bool()
			status_message = String()
		}
	}
}