// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct SetLightProperties: ServiceProt {
		public typealias Request = SetLightPropertiesRequest
		public typealias Response = SetLightPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "cd58c48ac21e5165abf13bcaa9c079b4"
		public static let datatype = "gazebo_msgs/SetLightProperties"
	}
}