// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct SetLinkState: ServiceProt {
		public typealias Request = SetLinkStateRequest
		public typealias Response = SetLinkStateResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "8a5146eb66ae4d26b0860b08f3f271be"
		public static let datatype = "gazebo_msgs/SetLinkState"
	}
}