// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension gazebo_msgs {

	public struct SetLightPropertiesRequest: ServiceMessage {
		public static let md5sum: String = "73ad1ac5e9e312ddf7c74f38ad843f34"
		public static let datatype = "gazebo_msgs/SetLightPropertiesRequest"
		public static var srvMd5sum: String = SetLightProperties.md5sum
		public static var srvDatatype: String = SetLightProperties.datatype
		public static let definition = """
			string light_name                    # name of Gazebo Light
			std_msgs/ColorRGBA diffuse           # diffuse color as red, green, blue, alpha
			float64 attenuation_constant
			float64 attenuation_linear
			float64 attenuation_quadratic
			"""

	
		public var light_name: String
		public var diffuse: std_msgs.ColorRGBA
		public var attenuation_constant: Float64
		public var attenuation_linear: Float64
		public var attenuation_quadratic: Float64

		public init(light_name: String, diffuse: std_msgs.ColorRGBA, attenuation_constant: Float64, attenuation_linear: Float64, attenuation_quadratic: Float64) {
			self.light_name = light_name
			self.diffuse = diffuse
			self.attenuation_constant = attenuation_constant
			self.attenuation_linear = attenuation_linear
			self.attenuation_quadratic = attenuation_quadratic
		}

		public init() {
			light_name = String()
			diffuse = std_msgs.ColorRGBA()
			attenuation_constant = Float64()
			attenuation_linear = Float64()
			attenuation_quadratic = Float64()
		}
	}
}