// Generated by msgbuilder 2020-05-10 06:44:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct SetLinkProperties: ServiceProt {
		public typealias Request = gazebo_msgs.SetLinkPropertiesRequest
		public typealias Response = gazebo_msgs.SetLinkPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "d534ce1b36ee99de0ffa806c3a6348f0"
		public static let datatype = "gazebo_msgs/SetLinkProperties"
	}
}