// Generated by msgbuilder 2020-05-14 06:44:12 +0000

import StdMsgs

extension gazebo_msgs {
	public enum SetLinkState: ServiceProt {
		public static let md5sum: String = "8a5146eb66ae4d26b0860b08f3f271be"
		public static let datatype = "gazebo_msgs/SetLinkState"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "22a2c757d56911b6f27868159e9a872d"
			public static let datatype = "gazebo_msgs/SetLinkStateRequest"
			public typealias ServiceType = SetLinkState
			public static let definition = """
				gazebo_msgs/LinkState link_state
				"""
	
		
			public var link_state: LinkState
	
			public init(link_state: LinkState) {
				self.link_state = link_state
			}
	
			public init() {
				link_state = LinkState()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "2ec6f3eff0161f4257b808b12bc830c2"
			public static let datatype = "gazebo_msgs/SetLinkStateResponse"
			public typealias ServiceType = SetLinkState
			public static let definition = """
				bool success                # return true if set wrench successful
				string status_message       # comments if available
				"""
	
		
			public var success: Bool
			public var status_message: String
	
			public init(success: Bool, status_message: String) {
				self.success = success
				self.status_message = status_message
			}
	
			public init() {
				success = Bool()
				status_message = String()
			}
		}

	}
}