// Generated by msgbuilder 2020-05-14 06:44:12 +0000

import StdMsgs

extension gazebo_msgs {
	public enum SetModelState: ServiceProt {
		public static let md5sum: String = "5b3ab0281d4f5445def017e3a2e4a07b"
		public static let datatype = "gazebo_msgs/SetModelState"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "cb042b0e91880f4661b29ea5b6234350"
			public static let datatype = "gazebo_msgs/SetModelStateRequest"
			public typealias ServiceType = SetModelState
			public static let definition = """
				gazebo_msgs/ModelState model_state
				"""
	
		
			public var model_state: ModelState
	
			public init(model_state: ModelState) {
				self.model_state = model_state
			}
	
			public init() {
				model_state = ModelState()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "2ec6f3eff0161f4257b808b12bc830c2"
			public static let datatype = "gazebo_msgs/SetModelStateResponse"
			public typealias ServiceType = SetModelState
			public static let definition = """
				bool success                  # return true if setting state successful
				string status_message         # comments if available
				"""
	
		
			public var success: Bool
			public var status_message: String
	
			public init(success: Bool, status_message: String) {
				self.success = success
				self.status_message = status_message
			}
	
			public init() {
				success = Bool()
				status_message = String()
			}
		}

	}
}