// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension gazebo_msgs {

	public struct SetModelStateRequest: ServiceMessage {
		public static let md5sum: String = "cb042b0e91880f4661b29ea5b6234350"
		public static let datatype = "gazebo_msgs/SetModelStateRequest"
		public static var srvMd5sum: String = SetModelState.md5sum
		public static var srvDatatype: String = SetModelState.datatype
		public static let definition = """
			gazebo_msgs/ModelState model_state
			"""

	
		public var model_state: ModelState

		public init(model_state: ModelState) {
			self.model_state = model_state
		}

		public init() {
			model_state = ModelState()
		}
	}
}