// Generated by msgbuilder 2020-05-10 06:44:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct SetModelConfiguration: ServiceProt {
		public typealias Request = gazebo_msgs.SetModelConfigurationRequest
		public typealias Response = gazebo_msgs.SetModelConfigurationResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "10e3139d3b669c40afc057d38956fff7"
		public static let datatype = "gazebo_msgs/SetModelConfiguration"
	}
}