// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct SetModelState: ServiceProt {
		public typealias Request = SetModelStateRequest
		public typealias Response = SetModelStateResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "5b3ab0281d4f5445def017e3a2e4a07b"
		public static let datatype = "gazebo_msgs/SetModelState"
	}
}