// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

extension gazebo_msgs {
	public struct SetPhysicsProperties: ServiceProt {
		public typealias Request = SetPhysicsPropertiesRequest
		public typealias Response = SetPhysicsPropertiesResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "97e2057080558ce4730434b5fae75c91"
		public static let datatype = "gazebo_msgs/SetPhysicsProperties"
	}
}