// Generated by msgbuilder 2020-05-10 10:56:43 +0000

import StdMsgs

extension gazebo_msgs {
	/// sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
	public struct SetPhysicsPropertiesRequest: ServiceMessage {
		public static let md5sum: String = "abd9f82732b52b92e9d6bb36e6a82452"
		public static let datatype = "gazebo_msgs/SetPhysicsPropertiesRequest"
		public static var srvMd5sum: String = SetPhysicsProperties.md5sum
		public static var srvDatatype: String = SetPhysicsProperties.datatype
		public static let definition = """
			# sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
			float64 time_step                  # dt in seconds
			float64 max_update_rate            # throttle maximum physics update rate
			geometry_msgs/Vector3 gravity      # gravity vector (e.g. earth ~[0,0,-9.81])
			gazebo_msgs/ODEPhysics ode_config  # configurations for ODE
			"""

	
		public var time_step: Float64
		public var max_update_rate: Float64
		public var gravity: geometry_msgs.Vector3
		public var ode_config: ODEPhysics

		public init(time_step: Float64, max_update_rate: Float64, gravity: geometry_msgs.Vector3, ode_config: ODEPhysics) {
			self.time_step = time_step
			self.max_update_rate = max_update_rate
			self.gravity = gravity
			self.ode_config = ode_config
		}

		public init() {
			time_step = Float64()
			max_update_rate = Float64()
			gravity = geometry_msgs.Vector3()
			ode_config = ODEPhysics()
		}
	}
}