// Generated by msgbuilder 2020-05-10 06:44:09 +0000

import StdMsgs

extension gazebo_msgs {
	public struct SpawnModel: ServiceProt {
		public typealias Request = gazebo_msgs.SpawnModelRequest
		public typealias Response = gazebo_msgs.SpawnModelResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "9ed9c82c96abe1a00c3e8cdaeee24413"
		public static let datatype = "gazebo_msgs/SpawnModel"
	}
}