import Foundation
import StdMsgs
import RosTime


extension nav_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
/// Get the map as a nav_msgs/OccupancyGrid
public struct GetMapGoal: Message {
public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
public static let datatype = "nav_msgs/GetMapGoal"
public static let definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Get the map as a nav_msgs/OccupancyGrid
"""

public init() {
    
}

}
}
