import Foundation
import StdMsgs
import RosTime


extension nav_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct GetMapAction: Message {
public static let md5sum: String = "e611ad23fbf237c031b7536416dc7cd7"
public static let datatype = "nav_msgs/GetMapAction"
public static let definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

GetMapActionGoal action_goal
GetMapActionResult action_result
GetMapActionFeedback action_feedback
"""

public var action_goal: GetMapActionGoal
public var action_result: GetMapActionResult
public var action_feedback: GetMapActionFeedback

public init(action_goal: GetMapActionGoal, action_result: GetMapActionResult, action_feedback: GetMapActionFeedback) {
self.action_goal = action_goal
self.action_result = action_result
self.action_feedback = action_feedback
}

public init() {
    action_goal = GetMapActionGoal()
action_result = GetMapActionResult()
action_feedback = GetMapActionFeedback()
}

}
}
