import Foundation
import StdMsgs
import RosTime
import nav_msgs

extension nav_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct GetMapResult: Message {
public static var md5sum: String = "6cdd0a18e0aff5b0a3ca2326a89b54ff"
public static var datatype = "nav_msgs/GetMapResult"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
nav_msgs/OccupancyGrid map
"""
public static var hasHeader = false

public var map: nav_msgs.OccupancyGrid

public init(map: nav_msgs.OccupancyGrid) {
self.map = map
}

public init() {
    map = nav_msgs.OccupancyGrid()
}

}
}
