import Foundation
import StdMsgs
import RosTime


extension nav_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct GetMapActionGoal: MessageWithHeader {
public static let md5sum: String = "4b30be6cd12b9e72826df56b481f40e0"
public static let datatype = "nav_msgs/GetMapActionGoal"
public static let definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
GetMapGoal goal
"""

public var header: std_msgs.Header
public var goal_id: actionlib_msgs.GoalID
public var goal: GetMapGoal

public init(header: std_msgs.Header, goal_id: actionlib_msgs.GoalID, goal: GetMapGoal) {
self.header = header
self.goal_id = goal_id
self.goal = goal
}

public init() {
    header = std_msgs.Header()
goal_id = actionlib_msgs.GoalID()
goal = GetMapGoal()
}

}
}
