import Foundation
import StdMsgs
import RosTime


extension nav_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
/// Get the map as a nav_msgs/OccupancyGrid
public struct GetMapGoal: Message {
public static var md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
public static var datatype = "nav_msgs/GetMapGoal"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Get the map as a nav_msgs/OccupancyGrid
"""
public static var hasHeader = false





public init() {
    
}

}
}
