import Foundation
import StdMsgs
import RosTime


extension nav_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
/// no feedback
public struct GetMapFeedback: Message {
public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
public static let datatype = "nav_msgs/GetMapFeedback"
public static let definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# no feedback
"""


public init() {
    
}

}
}
