// Generated by msgbuilder 2020-05-09 12:28:40 +0000

import StdMsgs

extension nav_msgs {

	public struct GetMapResponse: ServiceMessage {
		public static let md5sum: String = "6cdd0a18e0aff5b0a3ca2326a89b54ff"
		public static let datatype = "nav_msgs/GetMapResponse"
		public static var srvMd5sum: String = GetMap.md5sum
		public static var srvDatatype: String = GetMap.datatype
		public static let definition = """
			nav_msgs/OccupancyGrid map
			"""

	
		public var map: OccupancyGrid

		public init(map: OccupancyGrid) {
			self.map = map
		}

		public init() {
			map = OccupancyGrid()
		}
	}
}