import Foundation
import StdMsgs
import RosTime


extension nav_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct GetMapActionResult: MessageWithHeader {
public static let md5sum: String = "ac66e5b9a79bb4bbd33dab245236c892"
public static let datatype = "nav_msgs/GetMapActionResult"
public static let definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GetMapResult result
"""

public var header: std_msgs.Header
public var status: actionlib_msgs.GoalStatus
public var result: GetMapResult

public init(header: std_msgs.Header, status: actionlib_msgs.GoalStatus, result: GetMapResult) {
self.header = header
self.status = status
self.result = result
}

public init() {
    header = std_msgs.Header()
status = actionlib_msgs.GoalStatus()
result = GetMapResult()
}

}
}
