// Generated by msgbuilder 2020-05-12 11:56:11 +0000

import StdMsgs

extension nav_msgs {
	public struct GetMap: ServiceProt {
		public typealias Request = GetMapRequest
		public typealias Response = GetMapResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "6cdd0a18e0aff5b0a3ca2326a89b54ff"
		public static let datatype = "nav_msgs/GetMap"
	}
}