// Generated by msgbuilder 2020-05-09 12:28:40 +0000

import StdMsgs

extension nav_msgs {
	/// Get the map as a nav_msgs/OccupancyGrid
	public struct GetMapRequest: ServiceMessage {
		public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
		public static let datatype = "nav_msgs/GetMapRequest"
		public static var srvMd5sum: String = GetMap.md5sum
		public static var srvDatatype: String = GetMap.datatype
		public static let definition = """
			# Get the map as a nav_msgs/OccupancyGrid
			"""

	
	



		public init() {
	
		}
	}
}