// Generated by msgbuilder 2020-05-15 06:20:49 +0000

import StdMsgs

extension nav_msgs {
	public enum GetMap: ServiceProt {
		public static let md5sum: String = "6cdd0a18e0aff5b0a3ca2326a89b54ff"
		public static let datatype = "nav_msgs/GetMap"

		/// Get the map as a nav_msgs/OccupancyGrid
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
			public static let datatype = "nav_msgs/GetMapRequest"
			public typealias ServiceType = GetMap
			public static let definition = """
				# Get the map as a nav_msgs/OccupancyGrid
				"""
	
			public init() {
		
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "6cdd0a18e0aff5b0a3ca2326a89b54ff"
			public static let datatype = "nav_msgs/GetMapResponse"
			public typealias ServiceType = GetMap
			public static let definition = "nav_msgs/OccupancyGrid map"
	
			public var map: OccupancyGrid
	
			public init(map: OccupancyGrid) {
				self.map = map
			}
	
			public init() {
				map = OccupancyGrid()
			}
		}

	}
}