import Foundation
import StdMsgs
import RosTime


extension nav_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
/// no feedback
public struct GetMapFeedback: Message {
public static var md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
public static var datatype = "nav_msgs/GetMapFeedback"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# no feedback
"""
public static var hasHeader = false





public init() {
    
}

}
}
