// Generated by msgbuilder 2020-05-10 06:44:09 +0000

import StdMsgs

extension nav_msgs {
	public struct GetPlan: ServiceProt {
		public typealias Request = nav_msgs.GetPlanRequest
		public typealias Response = nav_msgs.GetPlanResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "421c8ea4d21c6c9db7054b4bbdf1e024"
		public static let datatype = "nav_msgs/GetPlan"
	}
}