// Generated by msgbuilder 2020-05-09 12:28:40 +0000

import StdMsgs

extension nav_msgs {

	public struct GetPlanResponse: ServiceMessage {
		public static let md5sum: String = "0002bc113c0259d71f6cf8cbc9430e18"
		public static let datatype = "nav_msgs/GetPlanResponse"
		public static var srvMd5sum: String = GetPlan.md5sum
		public static var srvDatatype: String = GetPlan.datatype
		public static let definition = """
			nav_msgs/Path plan
			"""

	
		public var plan: Path

		public init(plan: Path) {
			self.plan = plan
		}

		public init() {
			plan = Path()
		}
	}
}