// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

public enum nav_msgs {
    public static let all: [String: Message.Type] = [
        "GridCells": GridCells.self,
		"MapMetaData": MapMetaData.self,
		"OccupancyGrid": OccupancyGrid.self,
		"Odometry": Odometry.self,
		"Path": Path.self]
}