// Generated by msgbuilder 2020-05-09 12:28:40 +0000

import StdMsgs
import geometry_msgs

extension nav_msgs {
	/// Set a new map together with an initial pose
	public struct SetMapRequest: ServiceMessage {
		public static let md5sum: String = "91149a20d7be299b87c340df8cc94fd4"
		public static let datatype = "nav_msgs/SetMapRequest"
		public static var srvMd5sum: String = SetMap.md5sum
		public static var srvDatatype: String = SetMap.datatype
		public static let definition = """
			# Set a new map together with an initial pose
			nav_msgs/OccupancyGrid map
			geometry_msgs/PoseWithCovarianceStamped initial_pose
			"""

	
		public var map: OccupancyGrid
		public var initial_pose: geometry_msgs.PoseWithCovarianceStamped

		public init(map: OccupancyGrid, initial_pose: geometry_msgs.PoseWithCovarianceStamped) {
			self.map = map
			self.initial_pose = initial_pose
		}

		public init() {
			map = OccupancyGrid()
			initial_pose = geometry_msgs.PoseWithCovarianceStamped()
		}
	}
}