// Generated by msgbuilder 2020-05-10 06:44:09 +0000

import StdMsgs

extension nav_msgs {
	public struct SetMap: ServiceProt {
		public typealias Request = nav_msgs.SetMapRequest
		public typealias Response = nav_msgs.SetMapResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "c36922319011e63ed7784112ad4fdd32"
		public static let datatype = "nav_msgs/SetMap"
	}
}