// Generated by msgbuilder 2020-05-15 06:20:49 +0000

import StdMsgs

extension nav_msgs {
	public enum SetMap: ServiceProt {
		public static let md5sum: String = "c36922319011e63ed7784112ad4fdd32"
		public static let datatype = "nav_msgs/SetMap"

		/// Set a new map together with an initial pose
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "91149a20d7be299b87c340df8cc94fd4"
			public static let datatype = "nav_msgs/SetMapRequest"
			public typealias ServiceType = SetMap
			public static let definition = """
				# Set a new map together with an initial pose
				nav_msgs/OccupancyGrid map
				geometry_msgs/PoseWithCovarianceStamped initial_pose
				"""
	
			public var map: OccupancyGrid
			public var initial_pose: geometry_msgs.PoseWithCovarianceStamped
	
			public init(map: OccupancyGrid, initial_pose: geometry_msgs.PoseWithCovarianceStamped) {
				self.map = map
				self.initial_pose = initial_pose
			}
	
			public init() {
				map = OccupancyGrid()
				initial_pose = geometry_msgs.PoseWithCovarianceStamped()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "358e233cde0c8a8bcfea4ce193f8fc15"
			public static let datatype = "nav_msgs/SetMapResponse"
			public typealias ServiceType = SetMap
			public static let definition = "bool success"
	
			public var success: Bool
	
			public init(success: Bool) {
				self.success = success
			}
	
			public init() {
				success = Bool()
			}
		}

	}
}