// Generated by msgbuilder 2020-05-05 18:40:13 +0000

import RosTime
import StdMsgs

extension rosgraph_msgs {
	/// roslib/Clock is used for publishing simulated time in ROS. 
	/// This message simply communicates the current time.
	/// For more information, see http://www.ros.org/wiki/Clock
	public struct Clock: Message {
		public static let md5sum: String = "a9c97c1d230cfc112e270351a944ee47"
		public static let datatype = "rosgraph_msgs/Clock"
		public static let definition = """
			# roslib/Clock is used for publishing simulated time in ROS. 
			# This message simply communicates the current time.
			# For more information, see http://www.ros.org/wiki/Clock
			time clock
			"""

	
		public var clock: Time

		public init(clock: Time) {
			self.clock = clock
		}

		public init() {
			clock = Time()
		}
	}
}