// Generated by msgbuilder 2020-05-10 10:59:44 +0000

import StdMsgs

public enum rosgraph_msgs {
    public static let all: [String: Message.Type] = [
        "Clock": Clock.self,
		"Log": Log.self,
		"TopicStatistics": TopicStatistics.self]
}