//
//  AdvertiseSereviceOptions.swift
//  RosSwift
//
//  Created by Thomas Gustafsson on 2018-03-05.
//
import StdMsgs


typealias VoidFunc = () -> Void

/**

 - Todo: check service datatype
 */

final class AdvertiseServiceOptions<MReq: ServiceMessage, MRes: ServiceMessage> {
    var service : String
    var md5sum : String { return MReq.srv_md5sum }
    var datatype : String { return MReq.srv_datatype }
    var reqDatatype : String { return MReq.datatype }
    var resDatatype : String { return MRes.datatype }
    var helper : ServiceCallbackHelper?
    var tracked_object : VoidFunc?
    var callback : (MReq) -> MRes?

    init(service: String, callback: @escaping (MReq) -> MRes?) {

        guard MReq.srv_md5sum == MRes.srv_md5sum else {
            fatalError("the request and response parameters to the server "
               + "callback function must be autogenerated from the same "
               + "server definition file (.srv). your advertise_servce "
               + "call for \(service) appeared to use request/response types "
               + "from different .srv files.")
        }

        self.service = service
        self.callback = callback
    }

    
}
