//
//  AdvertiseServiceOptions.swift
//  RosSwift
//
//  Created by Thomas Gustafsson on 2018-03-05.
//
import StdMsgs

struct AdvertiseServiceOptions<MReq: ServiceMessage, MRes: ServiceMessage>: Sendable {
    let service: String
    var md5sum: String { return MReq.srvMd5sum }
    var datatype: String { return MReq.srvDatatype }
    var reqDatatype: String { return MReq.datatype }
    var resDatatype: String { return MRes.datatype }
    weak var trackedObject: TrackableObject?
    let callback: @Sendable (MReq) -> MRes?
    let callbackQueue: AsyncCallbackQueue?
    
    init(service: String, callback: @escaping @Sendable (MReq) -> MRes?, trackedObject: TrackableObject? = nil, callbackQueue: AsyncCallbackQueue? = nil) {
        
        guard MReq.srvMd5sum == MRes.srvMd5sum else {
            fatalError("the request and response parameters to the server "
                       + "callback function must be autogenerated from the same "
                       + "server definition file (.srv). your advertise_servce "
                       + "call for \(service) appeared to use request/response types "
                       + "from different .srv files.")
        }
        
        self.service = service
        self.callback = callback
        self.callbackQueue = callbackQueue
        self.trackedObject = trackedObject
    }
    
    func set(service: String) -> AdvertiseServiceOptions<MReq, MRes> {
        AdvertiseServiceOptions(service: service, callback: callback, trackedObject: trackedObject, callbackQueue: callbackQueue)
    }
    
    func set(callbackQueue: AsyncCallbackQueue?) -> AdvertiseServiceOptions<MReq, MRes> {
        AdvertiseServiceOptions(service: service, callback: callback, trackedObject: trackedObject, callbackQueue: callbackQueue)
    }
    
}
