//
//  AdvertiseSereviceOptions.swift
//  RosSwift
//
//  Created by Thomas Gustafsson on 2018-03-05.
//
import StdMsgs

final class AdvertiseServiceOptions<MReq: ServiceMessage, MRes: ServiceMessage> {
    var service: String
    var md5sum: String { return MReq.srvMd5sum }
    var datatype: String { return MReq.srvDatatype }
    var reqDatatype: String { return MReq.datatype }
    var resDatatype: String { return MRes.datatype }
    var trackedObject: AnyObject?
    var callback: (MReq) -> MRes?
    var callbackQueue: CallbackQueueInterface?

    init(service: String, callback: @escaping (MReq) -> MRes?) {

        guard MReq.srvMd5sum == MRes.srvMd5sum else {
            fatalError("the request and response parameters to the server "
               + "callback function must be autogenerated from the same "
               + "server definition file (.srv). your advertise_servce "
               + "call for \(service) appeared to use request/response types "
               + "from different .srv files.")
        }

        self.service = service
        self.callback = callback
    }

}
