import Foundation
import StdMsgs
import RosTime


extension actionlib {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct TestRequestResult: Message {
public static var md5sum: String = "61c2364524499c7c5017e2f3fce7ba06"
public static var datatype = "actionlib/TestRequestResult"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
int32 the_result
bool is_simple_server
"""
public static var hasHeader = false

public var the_result: Int32
public var is_simple_server: Bool

public init(the_result: Int32, is_simple_server: Bool) {
self.the_result = the_result
self.is_simple_server = is_simple_server
}

public init() {
    the_result = Int32()
is_simple_server = Bool()
}

}
}
