import Foundation
import StdMsgs
import RosTime

extension actionlib {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct TestActionResult: Message {
public static var md5sum: String = "3d669e3a63aa986c667ea7b0f46ce85e"
public static var datatype = "actionlib/TestActionResult"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
TestResult result
"""
public static var hasHeader = false

public var header: std_msgs.header
public var status: actionlib_msgs.GoalStatus
public var result: TestResult

public init(header: std_msgs.header, status: actionlib_msgs.GoalStatus, result: TestResult) {
self.header = header
self.status = status
self.result = result
}

public init() {
    header = std_msgs.header()
status = actionlib_msgs.GoalStatus()
result = TestResult()
}

}
}
