import Foundation
import StdMsgs
import RosTime


extension actionlib {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct TestRequestFeedback: Message {
public static var md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
public static var datatype = "actionlib/TestRequestFeedback"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
"""
public static var hasHeader = false





public init() {
    
}

}
}
