import Foundation
import StdMsgs
import RosTime


extension actionlib {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct TestAction: Message {
public static var md5sum: String = "991e87a72802262dfbe5d1b3cf6efc9a"
public static var datatype = "actionlib/TestAction"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

TestActionGoal action_goal
TestActionResult action_result
TestActionFeedback action_feedback
"""
public static var hasHeader = false

public var action_goal: TestActionGoal
public var action_result: TestActionResult
public var action_feedback: TestActionFeedback

public init(action_goal: TestActionGoal, action_result: TestActionResult, action_feedback: TestActionFeedback) {
self.action_goal = action_goal
self.action_result = action_result
self.action_feedback = action_feedback
}

public init() {
    action_goal = TestActionGoal()
action_result = TestActionResult()
action_feedback = TestActionFeedback()
}

}
}
