import Foundation
import StdMsgs
import RosTime


extension actionlib {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct TestFeedback: Message {
public static var md5sum: String = "49ceb5b32ea3af22073ede4a0328249e"
public static var datatype = "actionlib/TestFeedback"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
int32 feedback
"""
public static var hasHeader = false

public var feedback: Int32

public init(feedback: Int32) {
self.feedback = feedback
}

public init() {
    feedback = Int32()
}

}
}
