import Foundation
import StdMsgs
import RosTime


extension actionlib {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct TestResult: Message {
public static var md5sum: String = "034a8e20d6a306665e3a5b340fab3f09"
public static var datatype = "actionlib/TestResult"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
int32 result
"""
public static var hasHeader = false

public var result: Int32

public init(result: Int32) {
self.result = result
}

public init() {
    result = Int32()
}

}
}
