import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension actionlib {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct TwoIntsActionResult: Message {
public static var md5sum: String = "3ba7dea8b8cddcae4528ade4ef74b6e7"
public static var datatype = "actionlib/TwoIntsActionResult"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
TwoIntsResult result
"""
public static var hasHeader = false

public var header: std_msgs.header
public var status: actionlib_msgs.GoalStatus
public var result: TwoIntsResult

public init(header: std_msgs.header, status: actionlib_msgs.GoalStatus, result: TwoIntsResult) {
self.header = header
self.status = status
self.result = result
}

public init() {
    header = std_msgs.header()
status = actionlib_msgs.GoalStatus()
result = TwoIntsResult()
}

}
}
