import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension actionlib {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct TwoIntsActionGoal: Message {
public static var md5sum: String = "684a2db55d6ffb8046fb9d6764ce0860"
public static var datatype = "actionlib/TwoIntsActionGoal"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
TwoIntsGoal goal
"""
public static var hasHeader = false

public var header: std_msgs.header
public var goal_id: actionlib_msgs.GoalID
public var goal: TwoIntsGoal

public init(header: std_msgs.header, goal_id: actionlib_msgs.GoalID, goal: TwoIntsGoal) {
self.header = header
self.goal_id = goal_id
self.goal = goal
}

public init() {
    header = std_msgs.header()
goal_id = actionlib_msgs.GoalID()
goal = TwoIntsGoal()
}

}
}
