// Generated by msgbuilder 2019-05-02 07:55:41 +0000

import StdMsgs

extension geometry_msgs {
	/// This expresses acceleration in free space with uncertainty.
	/// Row-major representation of the 6x6 covariance matrix
	/// The orientation parameters use a fixed-axis representation.
	/// In order, the parameters are:
	/// (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
	public struct AccelWithCovariance: Message {
		public static let md5sum: String = "ad5a718d699c6be72a02b8d6a139f334"
		public static let datatype = "geometry_msgs/AccelWithCovariance"
		public static let definition = """
			# This expresses acceleration in free space with uncertainty.
			Accel accel
			# Row-major representation of the 6x6 covariance matrix
			# The orientation parameters use a fixed-axis representation.
			# In order, the parameters are:
			# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
			float64[36] covariance
			"""

		public static let hasHeader = false

	
		public var accel: Accel
		public var covariance: [Float64]

		public init(accel: Accel, covariance: [Float64]) {
			self.accel = accel
			assert(covariance.count == 36)
			self.covariance = covariance
		}

		public init() {
			accel = Accel()
			covariance = [Float64](repeating: 0, count: 36)
		}
	}
}