// Generated by msgbuilder 2020-05-10 10:59:44 +0000

import StdMsgs

public enum geometry_msgs {
    public static let all: [String: Message.Type] = [
        "PointStamped": PointStamped.self,
		"Point32": Point32.self,
		"PoseStamped": PoseStamped.self,
		"WrenchStamped": WrenchStamped.self,
		"QuaternionStamped": QuaternionStamped.self,
		"Twist": Twist.self,
		"Quaternion": Quaternion.self,
		"Pose2D": Pose2D.self,
		"AccelStamped": AccelStamped.self,
		"Vector3": Vector3.self,
		"AccelWithCovarianceStamped": AccelWithCovarianceStamped.self,
		"TwistStamped": TwistStamped.self,
		"Pose": Pose.self,
		"PoseWithCovariance": PoseWithCovariance.self,
		"PoseWithCovarianceStamped": PoseWithCovarianceStamped.self,
		"Transform": Transform.self,
		"PoseArray": PoseArray.self,
		"Point": Point.self,
		"TransformStamped": TransformStamped.self,
		"Inertia": Inertia.self,
		"Vector3Stamped": Vector3Stamped.self,
		"TwistWithCovarianceStamped": TwistWithCovarianceStamped.self,
		"Polygon": Polygon.self,
		"Wrench": Wrench.self,
		"AccelWithCovariance": AccelWithCovariance.self,
		"Accel": Accel.self,
		"PolygonStamped": PolygonStamped.self,
		"TwistWithCovariance": TwistWithCovariance.self,
		"InertiaStamped": InertiaStamped.self]
}