// Generated by msgbuilder 2019-05-02 07:55:41 +0000

import StdMsgs

extension geometry_msgs {
	/// This represents a Point with reference coordinate frame and timestamp
	public struct PointStamped: Message {
		public static let md5sum: String = "c63aecb41bfdfd6b7e1fac37c7cbe7bf"
		public static let datatype = "geometry_msgs/PointStamped"
		public static let definition = """
			# This represents a Point with reference coordinate frame and timestamp
			Header header
			Point point
			"""

		public static let hasHeader = true

	
		public var header: std_msgs.Header
		public var point: Point

		public init(header: std_msgs.Header, point: Point) {
			self.header = header
			self.point = point
		}

		public init() {
			header = std_msgs.Header()
			point = Point()
		}
	}
}