// Generated by msgbuilder 2019-05-02 07:55:41 +0000

import StdMsgs

extension geometry_msgs {
	/// This represents a Polygon with reference coordinate frame and timestamp
	public struct PolygonStamped: Message {
		public static let md5sum: String = "c6be8f7dc3bee7fe9e8d296070f53340"
		public static let datatype = "geometry_msgs/PolygonStamped"
		public static let definition = """
			# This represents a Polygon with reference coordinate frame and timestamp
			Header header
			Polygon polygon
			"""

		public static let hasHeader = true

	
		public var header: std_msgs.Header
		public var polygon: Polygon

		public init(header: std_msgs.Header, polygon: Polygon) {
			self.header = header
			self.polygon = polygon
		}

		public init() {
			header = std_msgs.Header()
			polygon = Polygon()
		}
	}
}