// Generated by msgbuilder 2019-05-02 07:55:41 +0000

import StdMsgs

extension geometry_msgs {
	/// This expresses a position and orientation on a 2D manifold.
	public struct Pose2D: Message {
		public static let md5sum: String = "938fa65709584ad8e77d238529be13b8"
		public static let datatype = "geometry_msgs/Pose2D"
		public static let definition = """
			# This expresses a position and orientation on a 2D manifold.
			float64 x
			float64 y
			float64 theta
			"""

		public static let hasHeader = false

	
		public var x: Float64
		public var y: Float64
		public var theta: Float64

		public init(x: Float64, y: Float64, theta: Float64) {
			self.x = x
			self.y = y
			self.theta = theta
		}

		public init() {
			x = Float64()
			y = Float64()
			theta = Float64()
		}
	}
}