// Generated by msgbuilder 2020-05-05 18:40:13 +0000

import StdMsgs

extension geometry_msgs {
	/// A Pose with reference coordinate frame and timestamp
	public struct PoseStamped: MessageWithHeader {
		public static let md5sum: String = "d3812c3cbc69362b77dc0b19b345f8f5"
		public static let datatype = "geometry_msgs/PoseStamped"
		public static let definition = """
			# A Pose with reference coordinate frame and timestamp
			Header header
			Pose pose
			"""

	
		public var header: std_msgs.Header
		public var pose: Pose

		public init(header: std_msgs.Header, pose: Pose) {
			self.header = header
			self.pose = pose
		}

		public init() {
			header = std_msgs.Header()
			pose = Pose()
		}
	}
}