// Generated by msgbuilder 2020-05-05 18:40:13 +0000

import StdMsgs

extension geometry_msgs {
	/// This represents an orientation with reference coordinate frame and timestamp.
	public struct QuaternionStamped: MessageWithHeader {
		public static let md5sum: String = "e57f1e547e0e1fd13504588ffc8334e2"
		public static let datatype = "geometry_msgs/QuaternionStamped"
		public static let definition = """
			# This represents an orientation with reference coordinate frame and timestamp.
			Header header
			Quaternion quaternion
			"""

	
		public var header: std_msgs.Header
		public var quaternion: Quaternion

		public init(header: std_msgs.Header, quaternion: Quaternion) {
			self.header = header
			self.quaternion = quaternion
		}

		public init() {
			header = std_msgs.Header()
			quaternion = Quaternion()
		}
	}
}