// Generated by msgbuilder 2019-05-02 07:55:41 +0000

import StdMsgs

extension geometry_msgs {
	/// This expresses a transform from coordinate frame header.frame_id
	/// to the coordinate frame child_frame_id
	///
	/// This message is mostly used by the 
	/// <a href="http://wiki.ros.org/tf">tf</a> package. 
	/// See its documentation for more information.
	public struct TransformStamped: Message {
		public static let md5sum: String = "b5764a33bfeb3588febc2682852579b0"
		public static let datatype = "geometry_msgs/TransformStamped"
		public static let definition = """
			# This expresses a transform from coordinate frame header.frame_id
			# to the coordinate frame child_frame_id
			#
			# This message is mostly used by the 
			# <a href="http://wiki.ros.org/tf">tf</a> package. 
			# See its documentation for more information.
			Header header
			string child_frame_id # the frame id of the child frame
			Transform transform
			"""

		public static let hasHeader = true

	
		public var header: std_msgs.Header
		public var child_frame_id: String
		public var transform: Transform

		public init(header: std_msgs.Header, child_frame_id: String, transform: Transform) {
			self.header = header
			self.child_frame_id = child_frame_id
			self.transform = transform
		}

		public init() {
			header = std_msgs.Header()
			child_frame_id = String()
			transform = Transform()
		}
	}
}