// Generated by msgbuilder 2020-05-05 18:40:13 +0000

import StdMsgs

extension geometry_msgs {
	/// This represents the transform between two coordinate frames in free space.
	public struct Transform: Message {
		public static let md5sum: String = "ac9eff44abf714214112b05d54a3cf9b"
		public static let datatype = "geometry_msgs/Transform"
		public static let definition = """
			# This represents the transform between two coordinate frames in free space.
			Vector3 translation
			Quaternion rotation
			"""

	
		public var translation: Vector3
		public var rotation: Quaternion

		public init(translation: Vector3, rotation: Quaternion) {
			self.translation = translation
			self.rotation = rotation
		}

		public init() {
			translation = Vector3()
			rotation = Quaternion()
		}
	}
}