// Generated by msgbuilder 2019-05-02 07:55:41 +0000

import StdMsgs

extension geometry_msgs {
	/// This represents an estimated twist with reference coordinate frame and timestamp.
	public struct TwistWithCovarianceStamped: Message {
		public static let md5sum: String = "8927a1a12fb2607ceea095b2dc440a96"
		public static let datatype = "geometry_msgs/TwistWithCovarianceStamped"
		public static let definition = """
			# This represents an estimated twist with reference coordinate frame and timestamp.
			Header header
			TwistWithCovariance twist
			"""

		public static let hasHeader = true

	
		public var header: std_msgs.Header
		public var twist: TwistWithCovariance

		public init(header: std_msgs.Header, twist: TwistWithCovariance) {
			self.header = header
			self.twist = twist
		}

		public init() {
			header = std_msgs.Header()
			twist = TwistWithCovariance()
		}
	}
}