// Generated by msgbuilder 2019-05-02 07:55:41 +0000

import StdMsgs

extension geometry_msgs {
	/// This represents a Vector3 with reference coordinate frame and timestamp
	public struct Vector3Stamped: Message {
		public static let md5sum: String = "7b324c7325e683bf02a9b14b01090ec7"
		public static let datatype = "geometry_msgs/Vector3Stamped"
		public static let definition = """
			# This represents a Vector3 with reference coordinate frame and timestamp
			Header header
			Vector3 vector
			"""

		public static let hasHeader = true

	
		public var header: std_msgs.Header
		public var vector: Vector3

		public init(header: std_msgs.Header, vector: Vector3) {
			self.header = header
			self.vector = vector
		}

		public init() {
			header = std_msgs.Header()
			vector = Vector3()
		}
	}
}