// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

public enum visualization_msgs {
    public static let all: [String: Message.Type] = [
        "ImageMarker": ImageMarker.self,
		"InteractiveMarker": InteractiveMarker.self,
		"InteractiveMarkerControl": InteractiveMarkerControl.self,
		"InteractiveMarkerFeedback": InteractiveMarkerFeedback.self,
		"InteractiveMarkerInit": InteractiveMarkerInit.self,
		"InteractiveMarkerPose": InteractiveMarkerPose.self,
		"InteractiveMarkerUpdate": InteractiveMarkerUpdate.self,
		"Marker": Marker.self,
		"MarkerArray": MarkerArray.self,
		"MenuEntry": MenuEntry.self]
}