import Foundation
import StdMsgs
import RosTime


extension tf2_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
///Simple API
///Advanced API
///Whether or not to use the advanced API
public struct LookupTransformGoal: Message {
public static var md5sum: String = "35e3720468131d675a18bb6f3e5f22f8"
public static var datatype = "tf2_msgs/LookupTransformGoal"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#Simple API
string target_frame
string source_frame
time source_time
duration timeout

#Advanced API
time target_time
string fixed_frame

#Whether or not to use the advanced API
bool advanced
"""
public static var hasHeader = false

public var target_frame: String
public var source_frame: String
public var source_time: RosTime.TimeBase
public var timeout: RosTime.Duration
public var target_time: RosTime.TimeBase
public var fixed_frame: String
public var advanced: Bool

public init(target_frame: String, source_frame: String, source_time: RosTime.TimeBase, timeout: RosTime.Duration, target_time: RosTime.TimeBase, fixed_frame: String, advanced: Bool) {
self.target_frame = target_frame
self.source_frame = source_frame
self.source_time = source_time
self.timeout = timeout
self.target_time = target_time
self.fixed_frame = fixed_frame
self.advanced = advanced
}

public init() {
    target_frame = String()
source_frame = String()
source_time = RosTime.TimeBase()
timeout = RosTime.Duration()
target_time = RosTime.TimeBase()
fixed_frame = String()
advanced = Bool()
}

}
}
