import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension tf2_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct LookupTransformActionResult: Message {
public static var md5sum: String = "ac26ce75a41384fa8bb4dc10f491ab90"
public static var datatype = "tf2_msgs/LookupTransformActionResult"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
LookupTransformResult result
"""
public static var hasHeader = false

public var header: std_msgs.header
public var status: actionlib_msgs.GoalStatus
public var result: LookupTransformResult

public init(header: std_msgs.header, status: actionlib_msgs.GoalStatus, result: LookupTransformResult) {
self.header = header
self.status = status
self.result = result
}

public init() {
    header = std_msgs.header()
status = actionlib_msgs.GoalStatus()
result = LookupTransformResult()
}

}
}
