import Foundation
import StdMsgs
import RosTime


extension tf2_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct LookupTransformAction: Message {
public static var md5sum: String = "7ee01ba91a56c2245c610992dbaa3c37"
public static var datatype = "tf2_msgs/LookupTransformAction"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

LookupTransformActionGoal action_goal
LookupTransformActionResult action_result
LookupTransformActionFeedback action_feedback
"""
public static var hasHeader = false

public var action_goal: LookupTransformActionGoal
public var action_result: LookupTransformActionResult
public var action_feedback: LookupTransformActionFeedback

public init(action_goal: LookupTransformActionGoal, action_result: LookupTransformActionResult, action_feedback: LookupTransformActionFeedback) {
self.action_goal = action_goal
self.action_result = action_result
self.action_feedback = action_feedback
}

public init() {
    action_goal = LookupTransformActionGoal()
action_result = LookupTransformActionResult()
action_feedback = LookupTransformActionFeedback()
}

}
}
