// Generated by msgbuilder 2019-05-02 07:55:41 +0000

import StdMsgs

extension sensor_msgs {

	public struct FluidPressure: Message {
		public static let md5sum: String = "804dc5cea1c5306d6a2eb80b9833befe"
		public static let datatype = "sensor_msgs/FluidPressure"
		public static let definition = """
			 # Single pressure reading.  This message is appropriate for measuring the
			 # pressure inside of a fluid (air, water, etc).  This also includes
			 # atmospheric or barometric pressure.
			 # This message is not appropriate for force/pressure contact sensors.
			 Header header           # timestamp of the measurement
			                         # frame_id is the location of the pressure sensor
			 float64 fluid_pressure  # Absolute pressure reading in Pascals.
			 float64 variance        # 0 is interpreted as variance unknown
			"""

		public static let hasHeader = true

	
		public var header: std_msgs.Header
		public var fluid_pressure: Float64
		public var variance: Float64

		public init(header: std_msgs.Header, fluid_pressure: Float64, variance: Float64) {
			self.header = header
			self.fluid_pressure = fluid_pressure
			self.variance = variance
		}

		public init() {
			header = std_msgs.Header()
			fluid_pressure = Float64()
			variance = Float64()
		}
	}
}