// Generated by msgbuilder 2019-05-02 07:55:41 +0000

import StdMsgs

extension sensor_msgs {
	/// This message holds the description of one point entry in the
	/// PointCloud2 message format.
	public struct PointField: Message {
		public static let md5sum: String = "633fa7ef352c25a9174af43be820c238"
		public static let datatype = "sensor_msgs/PointField"
		public static let definition = """
			# This message holds the description of one point entry in the
			# PointCloud2 message format.
			uint8 INT8    = 1
			uint8 UINT8   = 2
			uint8 INT16   = 3
			uint8 UINT16  = 4
			uint8 INT32   = 5
			uint8 UINT32  = 6
			uint8 FLOAT32 = 7
			uint8 FLOAT64 = 8
			string name      # Name of field
			uint32 offset    # Offset from start of point struct
			uint8  datatype  # Datatype enumeration, see above
			uint32 count     # How many elements in the field
			"""

		public static let hasHeader = false

		public static let INT8 : UInt8 = 1
		public static let UINT8 : UInt8 = 2
		public static let INT16 : UInt8 = 3
		public static let UINT16 : UInt8 = 4
		public static let INT32 : UInt8 = 5
		public static let UINT32 : UInt8 = 6
		public static let FLOAT32 : UInt8 = 7
		public static let FLOAT64 : UInt8 = 8
		public var name: String
		public var offset: UInt32
		public var _datatype: UInt8
		public var count: UInt32

		public init(name: String, offset: UInt32, _datatype: UInt8, count: UInt32) {
			self.name = name
			self.offset = offset
			self._datatype = _datatype
			self.count = count
		}

		public init() {
			name = String()
			offset = UInt32()
			_datatype = UInt8()
			count = UInt32()
		}
	}
}