// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

public enum sensor_msgs {
    public static let all: [String: Message.Type] = [
        "BatteryState": BatteryState.self,
		"CameraInfo": CameraInfo.self,
		"ChannelFloat32": ChannelFloat32.self,
		"CompressedImage": CompressedImage.self,
		"FluidPressure": FluidPressure.self,
		"Illuminance": Illuminance.self,
		"Image": Image.self,
		"Imu": Imu.self,
		"JointState": JointState.self,
		"Joy": Joy.self,
		"JoyFeedback": JoyFeedback.self,
		"JoyFeedbackArray": JoyFeedbackArray.self,
		"LaserEcho": LaserEcho.self,
		"LaserScan": LaserScan.self,
		"MagneticField": MagneticField.self,
		"MultiDOFJointState": MultiDOFJointState.self,
		"MultiEchoLaserScan": MultiEchoLaserScan.self,
		"NavSatFix": NavSatFix.self,
		"NavSatStatus": NavSatStatus.self,
		"PointCloud": PointCloud.self,
		"PointCloud2": PointCloud2.self,
		"PointField": PointField.self,
		"Range": Range.self,
		"RegionOfInterest": RegionOfInterest.self,
		"RelativeHumidity": RelativeHumidity.self,
		"Temperature": Temperature.self,
		"TimeReference": TimeReference.self]
}