// Generated by msgbuilder 2020-05-12 11:56:11 +0000

import StdMsgs

extension sensor_msgs {
	public struct SetCameraInfo: ServiceProt {
		public typealias Request = SetCameraInfoRequest
		public typealias Response = SetCameraInfoResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "bef1df590ed75ed1f393692395e15482"
		public static let datatype = "sensor_msgs/SetCameraInfo"
	}
}