// Generated by msgbuilder 2020-05-09 12:28:40 +0000

import StdMsgs

extension sensor_msgs {

	public struct SetCameraInfoResponse: ServiceMessage {
		public static let md5sum: String = "2ec6f3eff0161f4257b808b12bc830c2"
		public static let datatype = "sensor_msgs/SetCameraInfoResponse"
		public static var srvMd5sum: String = SetCameraInfo.md5sum
		public static var srvDatatype: String = SetCameraInfo.datatype
		public static let definition = """
			bool success          # True if the call succeeded
			string status_message # Used to give details about success
			"""

	
		public var success: Bool
		public var status_message: String

		public init(success: Bool, status_message: String) {
			self.success = success
			self.status_message = status_message
		}

		public init() {
			success = Bool()
			status_message = String()
		}
	}
}