// Generated by msgbuilder 2020-05-10 06:44:10 +0000

import StdMsgs

extension sensor_msgs {
	public struct SetCameraInfo: ServiceProt {
		public typealias Request = sensor_msgs.SetCameraInfoRequest
		public typealias Response = sensor_msgs.SetCameraInfoResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "bef1df590ed75ed1f393692395e15482"
		public static let datatype = "sensor_msgs/SetCameraInfo"
	}
}