// Generated by msgbuilder 2020-05-15 06:20:49 +0000

import StdMsgs

extension sensor_msgs {

	public struct Temperature: MessageWithHeader {
		public static let md5sum: String = "ff71b307acdbe7c871a5a6d7ed359100"
		public static let datatype = "sensor_msgs/Temperature"
		public static let definition = """
			 # Single temperature reading.
			 Header header           # timestamp is the time the temperature was measured
			                         # frame_id is the location of the temperature reading
			 float64 temperature     # Measurement of the Temperature in Degrees Celsius
			 float64 variance        # 0 is interpreted as variance unknown
			"""

		public var header: std_msgs.Header
		public var temperature: Float64
		public var variance: Float64

		public init(header: std_msgs.Header, temperature: Float64, variance: Float64) {
			self.header = header
			self.temperature = temperature
			self.variance = variance
		}

		public init() {
			header = std_msgs.Header()
			temperature = Float64()
			variance = Float64()
		}
	}
}