// Generated by msgbuilder 2019-05-02 07:55:41 +0000

import RosTime
import StdMsgs

extension sensor_msgs {
	/// Measurement from an external time source not actively synchronized with the system clock.
	public struct TimeReference: Message {
		public static let md5sum: String = "fded64a0265108ba86c3d38fb11c0c16"
		public static let datatype = "sensor_msgs/TimeReference"
		public static let definition = """
			# Measurement from an external time source not actively synchronized with the system clock.
			Header header    # stamp is system time for which measurement was valid
			                 # frame_id is not used 
			time   time_ref  # corresponding time from this external source
			string source    # (optional) name of time source
			"""

		public static let hasHeader = true

	
		public var header: std_msgs.Header
		public var time_ref: Time
		public var source: String

		public init(header: std_msgs.Header, time_ref: Time, source: String) {
			self.header = header
			self.time_ref = time_ref
			self.source = source
		}

		public init() {
			header = std_msgs.Header()
			time_ref = Time()
			source = String()
		}
	}
}