import Foundation
import StdMsgs
import RosTime


extension actionlib_tutorials {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
///goal definition
public struct AveragingGoal: Message {
public static var md5sum: String = "32c9b10ef9b253faa93b93f564762c8f"
public static var datatype = "actionlib_tutorials/AveragingGoal"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
int32 samples
"""
public static var hasHeader = false

public var samples: Int32

public init(samples: Int32) {
self.samples = samples
}

public init() {
    samples = Int32()
}

}
}
