import Foundation
import StdMsgs
import RosTime


extension actionlib_tutorials {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
///feedback
public struct AveragingFeedback: Message {
public static var md5sum: String = "9e8dfc53c2f2a032ca33fa80ec46fd4f"
public static var datatype = "actionlib_tutorials/AveragingFeedback"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#feedback
int32 sample
float32 data
float32 mean
float32 std_dev
"""
public static var hasHeader = false

public var sample: Int32
public var data: Float32
public var mean: Float32
public var std_dev: Float32

public init(sample: Int32, data: Float32, mean: Float32, std_dev: Float32) {
self.sample = sample
self.data = data
self.mean = mean
self.std_dev = std_dev
}

public init() {
    sample = Int32()
data = Float32()
mean = Float32()
std_dev = Float32()
}

}
}
