import Foundation
import StdMsgs
import RosTime


extension actionlib_tutorials {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct AveragingAction: Message {
public static var md5sum: String = "628678f2b4fa6a5951746a4a2d39e716"
public static var datatype = "actionlib_tutorials/AveragingAction"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

AveragingActionGoal action_goal
AveragingActionResult action_result
AveragingActionFeedback action_feedback
"""
public static var hasHeader = false

public var action_goal: AveragingActionGoal
public var action_result: AveragingActionResult
public var action_feedback: AveragingActionFeedback

public init(action_goal: AveragingActionGoal, action_result: AveragingActionResult, action_feedback: AveragingActionFeedback) {
self.action_goal = action_goal
self.action_result = action_result
self.action_feedback = action_feedback
}

public init() {
    action_goal = AveragingActionGoal()
action_result = AveragingActionResult()
action_feedback = AveragingActionFeedback()
}

}
}
