import Foundation
import StdMsgs
import RosTime


extension actionlib_tutorials {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct FibonacciAction: Message {
public static var md5sum: String = "f59df5767bf7634684781c92598b2406"
public static var datatype = "actionlib_tutorials/FibonacciAction"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

FibonacciActionGoal action_goal
FibonacciActionResult action_result
FibonacciActionFeedback action_feedback
"""
public static var hasHeader = false

public var action_goal: FibonacciActionGoal
public var action_result: FibonacciActionResult
public var action_feedback: FibonacciActionFeedback

public init(action_goal: FibonacciActionGoal, action_result: FibonacciActionResult, action_feedback: FibonacciActionFeedback) {
self.action_goal = action_goal
self.action_result = action_result
self.action_feedback = action_feedback
}

public init() {
    action_goal = FibonacciActionGoal()
action_result = FibonacciActionResult()
action_feedback = FibonacciActionFeedback()
}

}
}
