import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension actionlib_tutorials {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct FibonacciActionFeedback: Message {
public static var md5sum: String = "73b8497a9f629a31c0020900e4148f07"
public static var datatype = "actionlib_tutorials/FibonacciActionFeedback"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
FibonacciFeedback feedback
"""
public static var hasHeader = false

public var header: std_msgs.header
public var status: actionlib_msgs.GoalStatus
public var feedback: FibonacciFeedback

public init(header: std_msgs.header, status: actionlib_msgs.GoalStatus, feedback: FibonacciFeedback) {
self.header = header
self.status = status
self.feedback = feedback
}

public init() {
    header = std_msgs.header()
status = actionlib_msgs.GoalStatus()
feedback = FibonacciFeedback()
}

}
}
