import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension actionlib_tutorials {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct FibonacciActionGoal: Message {
public static var md5sum: String = "006871c7fa1d0e3d5fe2226bf17b2a94"
public static var datatype = "actionlib_tutorials/FibonacciActionGoal"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
FibonacciGoal goal
"""
public static var hasHeader = false

public var header: std_msgs.header
public var goal_id: actionlib_msgs.GoalID
public var goal: FibonacciGoal

public init(header: std_msgs.header, goal_id: actionlib_msgs.GoalID, goal: FibonacciGoal) {
self.header = header
self.goal_id = goal_id
self.goal = goal
}

public init() {
    header = std_msgs.header()
goal_id = actionlib_msgs.GoalID()
goal = FibonacciGoal()
}

}
}
