// Generated by msgbuilder 2020-05-10 06:44:10 +0000

import StdMsgs

extension diagnostic_msgs {
	public struct AddDiagnostics: ServiceProt {
		public typealias Request = diagnostic_msgs.AddDiagnosticsRequest
		public typealias Response = diagnostic_msgs.AddDiagnosticsResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "e6ac9bbde83d0d3186523c3687aecaee"
		public static let datatype = "diagnostic_msgs/AddDiagnostics"
	}
}