// Generated by msgbuilder 2020-05-12 11:56:11 +0000

import StdMsgs

extension diagnostic_msgs {
	public struct AddDiagnostics: ServiceProt {
		public typealias Request = AddDiagnosticsRequest
		public typealias Response = AddDiagnosticsResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "e6ac9bbde83d0d3186523c3687aecaee"
		public static let datatype = "diagnostic_msgs/AddDiagnostics"
	}
}