// Generated by msgbuilder 2020-05-10 10:56:43 +0000

import StdMsgs

public enum diagnostic_msgs {
    public static let all: [String: Message.Type] = [
        "DiagnosticStatus": DiagnosticStatus.self,
		"KeyValue": KeyValue.self,
		"DiagnosticArray": DiagnosticArray.self]
}