// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

public enum diagnostic_msgs {
    public static let all: [String: Message.Type] = [
        "DiagnosticArray": DiagnosticArray.self,
		"DiagnosticStatus": DiagnosticStatus.self,
		"KeyValue": KeyValue.self]
}