// Generated by msgbuilder 2020-05-09 12:28:40 +0000

import StdMsgs

extension diagnostic_msgs {

	public struct SelfTestRequest: ServiceMessage {
		public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
		public static let datatype = "diagnostic_msgs/SelfTestRequest"
		public static var srvMd5sum: String = SelfTest.md5sum
		public static var srvDatatype: String = SelfTest.datatype
		public static let definition = """
			
			"""

	
	



		public init() {
	
		}
	}
}