// Generated by msgbuilder 2020-05-10 05:59:01 +0000

import StdMsgs

extension diagnostic_msgs {
	public struct SelfTest: ServiceProt {
		public typealias Request = diagnostic_msgs.SelfTestRequest
		public typealias Response = diagnostic_msgs.SelfTestResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "36017f81f034610a27eda23327c2767c"
		public static let datatype = "diagnostic_msgs/SelfTest"
	}
}