// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

public enum control_msgs {
    public static let all: [String: Message.Type] = [
        "GripperCommand": GripperCommand.self,
		"JointControllerState": JointControllerState.self,
		"JointJog": JointJog.self,
		"JointTolerance": JointTolerance.self,
		"JointTrajectoryControllerState": JointTrajectoryControllerState.self,
		"PidState": PidState.self]
}