// Generated by msgbuilder 2020-05-10 10:59:44 +0000

import StdMsgs

public enum control_msgs {
    public static let all: [String: Message.Type] = [
        "JointJog": JointJog.self,
		"JointControllerState": JointControllerState.self,
		"JointTolerance": JointTolerance.self,
		"GripperCommand": GripperCommand.self,
		"PidState": PidState.self,
		"JointTrajectoryControllerState": JointTrajectoryControllerState.self]
}