import Foundation
import StdMsgs
import RosTime


extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct FollowJointTrajectoryAction: Message {
public static var md5sum: String = "bc4f9b743838566551c0390c65f1a248"
public static var datatype = "control_msgs/FollowJointTrajectoryAction"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

FollowJointTrajectoryActionGoal action_goal
FollowJointTrajectoryActionResult action_result
FollowJointTrajectoryActionFeedback action_feedback
"""
public static var hasHeader = false

public var action_goal: FollowJointTrajectoryActionGoal
public var action_result: FollowJointTrajectoryActionResult
public var action_feedback: FollowJointTrajectoryActionFeedback

public init(action_goal: FollowJointTrajectoryActionGoal, action_result: FollowJointTrajectoryActionResult, action_feedback: FollowJointTrajectoryActionFeedback) {
self.action_goal = action_goal
self.action_result = action_result
self.action_feedback = action_feedback
}

public init() {
    action_goal = FollowJointTrajectoryActionGoal()
action_result = FollowJointTrajectoryActionResult()
action_feedback = FollowJointTrajectoryActionFeedback()
}

}
}
