import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct GripperCommandActionGoal: Message {
public static var md5sum: String = "aa581f648a35ed681db2ec0bf7a82bea"
public static var datatype = "control_msgs/GripperCommandActionGoal"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
GripperCommandGoal goal
"""
public static var hasHeader = false

public var header: std_msgs.header
public var goal_id: actionlib_msgs.GoalID
public var goal: GripperCommandGoal

public init(header: std_msgs.header, goal_id: actionlib_msgs.GoalID, goal: GripperCommandGoal) {
self.header = header
self.goal_id = goal_id
self.goal = goal
}

public init() {
    header = std_msgs.header()
goal_id = actionlib_msgs.GoalID()
goal = GripperCommandGoal()
}

}
}
