import Foundation
import StdMsgs
import RosTime


extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct GripperCommandFeedback: Message {
public static var md5sum: String = "e4cbff56d3562bcf113da5a5adeef91f"
public static var datatype = "control_msgs/GripperCommandFeedback"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float64 position  # The current gripper gap size (in meters)
float64 effort    # The current effort exerted (in Newtons)
bool stalled      # True iff the gripper is exerting max effort and not moving
bool reached_goal # True iff the gripper position has reached the commanded setpoint
"""
public static var hasHeader = false

public var position: Float64
public var effort: Float64
public var stalled: Bool
public var reached_goal: Bool

public init(position: Float64, effort: Float64, stalled: Bool, reached_goal: Bool) {
self.position = position
self.effort = effort
self.stalled = stalled
self.reached_goal = reached_goal
}

public init() {
    position = Float64()
effort = Float64()
stalled = Bool()
reached_goal = Bool()
}

}
}
