import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct GripperCommandActionFeedback: Message {
public static var md5sum: String = "653dff30c045f5e6ff3feb3409f4558d"
public static var datatype = "control_msgs/GripperCommandActionFeedback"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GripperCommandFeedback feedback
"""
public static var hasHeader = false

public var header: std_msgs.header
public var status: actionlib_msgs.GoalStatus
public var feedback: GripperCommandFeedback

public init(header: std_msgs.header, status: actionlib_msgs.GoalStatus, feedback: GripperCommandFeedback) {
self.header = header
self.status = status
self.feedback = feedback
}

public init() {
    header = std_msgs.header()
status = actionlib_msgs.GoalStatus()
feedback = GripperCommandFeedback()
}

}
}
