import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct GripperCommandActionResult: Message {
public static var md5sum: String = "143702cb2df0f163c5283cedc5efc6b6"
public static var datatype = "control_msgs/GripperCommandActionResult"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GripperCommandResult result
"""
public static var hasHeader = false

public var header: std_msgs.header
public var status: actionlib_msgs.GoalStatus
public var result: GripperCommandResult

public init(header: std_msgs.header, status: actionlib_msgs.GoalStatus, result: GripperCommandResult) {
self.header = header
self.status = status
self.result = result
}

public init() {
    header = std_msgs.header()
status = actionlib_msgs.GoalStatus()
result = GripperCommandResult()
}

}
}
