import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct JointTrajectoryActionGoal: Message {
public static var md5sum: String = "a99e83ef6185f9fdd7693efe99623a86"
public static var datatype = "control_msgs/JointTrajectoryActionGoal"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
JointTrajectoryGoal goal
"""
public static var hasHeader = false

public var header: std_msgs.header
public var goal_id: actionlib_msgs.GoalID
public var goal: JointTrajectoryGoal

public init(header: std_msgs.header, goal_id: actionlib_msgs.GoalID, goal: JointTrajectoryGoal) {
self.header = header
self.goal_id = goal_id
self.goal = goal
}

public init() {
    header = std_msgs.header()
goal_id = actionlib_msgs.GoalID()
goal = JointTrajectoryGoal()
}

}
}
