import Foundation
import StdMsgs
import RosTime


extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct JointTrajectoryFeedback: Message {
public static var md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
public static var datatype = "control_msgs/JointTrajectoryFeedback"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
"""
public static var hasHeader = false





public init() {
    
}

}
}
