import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct JointTrajectoryActionResult: Message {
public static var md5sum: String = "1eb06eeff08fa7ea874431638cb52332"
public static var datatype = "control_msgs/JointTrajectoryActionResult"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
JointTrajectoryResult result
"""
public static var hasHeader = false

public var header: std_msgs.header
public var status: actionlib_msgs.GoalStatus
public var result: JointTrajectoryResult

public init(header: std_msgs.header, status: actionlib_msgs.GoalStatus, result: JointTrajectoryResult) {
self.header = header
self.status = status
self.result = result
}

public init() {
    header = std_msgs.header()
status = actionlib_msgs.GoalStatus()
result = JointTrajectoryResult()
}

}
}
