import Foundation
import StdMsgs
import RosTime


extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct JointTrajectoryAction: Message {
public static var md5sum: String = "a04ba3ee8f6a2d0985a6aeaf23d9d7ad"
public static var datatype = "control_msgs/JointTrajectoryAction"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

JointTrajectoryActionGoal action_goal
JointTrajectoryActionResult action_result
JointTrajectoryActionFeedback action_feedback
"""
public static var hasHeader = false

public var action_goal: JointTrajectoryActionGoal
public var action_result: JointTrajectoryActionResult
public var action_feedback: JointTrajectoryActionFeedback

public init(action_goal: JointTrajectoryActionGoal, action_result: JointTrajectoryActionResult, action_feedback: JointTrajectoryActionFeedback) {
self.action_goal = action_goal
self.action_result = action_result
self.action_feedback = action_feedback
}

public init() {
    action_goal = JointTrajectoryActionGoal()
action_result = JointTrajectoryActionResult()
action_feedback = JointTrajectoryActionFeedback()
}

}
}
