import Foundation
import StdMsgs
import RosTime


extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct PointHeadFeedback: Message {
public static var md5sum: String = "cce80d27fd763682da8805a73316cab4"
public static var datatype = "control_msgs/PointHeadFeedback"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float64 pointing_angle_error
"""
public static var hasHeader = false

public var pointing_angle_error: Float64

public init(pointing_angle_error: Float64) {
self.pointing_angle_error = pointing_angle_error
}

public init() {
    pointing_angle_error = Float64()
}

}
}
