import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct PointHeadActionGoal: Message {
public static var md5sum: String = "b53a8323d0ba7b310ba17a2d3a82a6b8"
public static var datatype = "control_msgs/PointHeadActionGoal"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
PointHeadGoal goal
"""
public static var hasHeader = false

public var header: std_msgs.header
public var goal_id: actionlib_msgs.GoalID
public var goal: PointHeadGoal

public init(header: std_msgs.header, goal_id: actionlib_msgs.GoalID, goal: PointHeadGoal) {
self.header = header
self.goal_id = goal_id
self.goal = goal
}

public init() {
    header = std_msgs.header()
goal_id = actionlib_msgs.GoalID()
goal = PointHeadGoal()
}

}
}
