// Generated by msgbuilder 2020-05-10 06:44:09 +0000

import StdMsgs

extension control_msgs {
	public struct QueryTrajectoryState: ServiceProt {
		public typealias Request = control_msgs.QueryTrajectoryStateRequest
		public typealias Response = control_msgs.QueryTrajectoryStateResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "ec93cdecbd8062d761aa52b7c90cd44b"
		public static let datatype = "control_msgs/QueryTrajectoryState"
	}
}