// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension control_msgs {

	public struct QueryCalibrationStateResponse: ServiceMessage {
		public static let md5sum: String = "28af3beedcb84986b8e470dc5470507d"
		public static let datatype = "control_msgs/QueryCalibrationStateResponse"
		public static var srvMd5sum: String = QueryCalibrationState.md5sum
		public static var srvDatatype: String = QueryCalibrationState.datatype
		public static let definition = """
			bool is_calibrated
			"""

	
		public var is_calibrated: Bool

		public init(is_calibrated: Bool) {
			self.is_calibrated = is_calibrated
		}

		public init() {
			is_calibrated = Bool()
		}
	}
}