// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension control_msgs {

	public struct QueryCalibrationStateRequest: ServiceMessage {
		public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
		public static let datatype = "control_msgs/QueryCalibrationStateRequest"
		public static var srvMd5sum: String = QueryCalibrationState.md5sum
		public static var srvDatatype: String = QueryCalibrationState.datatype
		public static let definition = """
			
			"""

	
	



		public init() {
	
		}
	}
}