// Generated by msgbuilder 2020-05-15 06:20:49 +0000

import StdMsgs

extension control_msgs {
	public enum QueryCalibrationState: ServiceProt {
		public static let md5sum: String = "28af3beedcb84986b8e470dc5470507d"
		public static let datatype = "control_msgs/QueryCalibrationState"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
			public static let datatype = "control_msgs/QueryCalibrationStateRequest"
			public typealias ServiceType = QueryCalibrationState
			public static let definition = ""
	
			public init() {
		
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "28af3beedcb84986b8e470dc5470507d"
			public static let datatype = "control_msgs/QueryCalibrationStateResponse"
			public typealias ServiceType = QueryCalibrationState
			public static let definition = "bool is_calibrated"
	
			public var is_calibrated: Bool
	
			public init(is_calibrated: Bool) {
				self.is_calibrated = is_calibrated
			}
	
			public init() {
				is_calibrated = Bool()
			}
		}

	}
}