// Generated by msgbuilder 2020-05-15 06:20:49 +0000

import RosTime
import StdMsgs

extension control_msgs {
	public enum QueryTrajectoryState: ServiceProt {
		public static let md5sum: String = "ec93cdecbd8062d761aa52b7c90cd44b"
		public static let datatype = "control_msgs/QueryTrajectoryState"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "556a4fb76023a469987922359d08a844"
			public static let datatype = "control_msgs/QueryTrajectoryStateRequest"
			public typealias ServiceType = QueryTrajectoryState
			public static let definition = "time time"
	
			public var time: Time
	
			public init(time: Time) {
				self.time = time
			}
	
			public init() {
				time = Time()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "1f1a6554ad060f44d013e71868403c1a"
			public static let datatype = "control_msgs/QueryTrajectoryStateResponse"
			public typealias ServiceType = QueryTrajectoryState
			public static let definition = """
				string[] name
				float64[] position
				float64[] velocity
				float64[] acceleration
				"""
	
			public var name: [String]
			public var position: [Float64]
			public var velocity: [Float64]
			public var acceleration: [Float64]
	
			public init(name: [String], position: [Float64], velocity: [Float64], acceleration: [Float64]) {
				self.name = name
				self.position = position
				self.velocity = velocity
				self.acceleration = acceleration
			}
	
			public init() {
				name = [String]()
				position = [Float64]()
				velocity = [Float64]()
				acceleration = [Float64]()
			}
		}

	}
}