// Generated by msgbuilder 2020-05-10 05:59:01 +0000

import StdMsgs

extension control_msgs {
	public struct QueryCalibrationState: ServiceProt {
		public typealias Request = control_msgs.QueryCalibrationStateRequest
		public typealias Response = control_msgs.QueryCalibrationStateResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "28af3beedcb84986b8e470dc5470507d"
		public static let datatype = "control_msgs/QueryCalibrationState"
	}
}