// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import RosTime
import StdMsgs

extension control_msgs {

	public struct QueryTrajectoryStateRequest: ServiceMessage {
		public static let md5sum: String = "556a4fb76023a469987922359d08a844"
		public static let datatype = "control_msgs/QueryTrajectoryStateRequest"
		public static var srvMd5sum: String = QueryTrajectoryState.md5sum
		public static var srvDatatype: String = QueryTrajectoryState.datatype
		public static let definition = """
			time time
			"""

	
		public var time: Time

		public init(time: Time) {
			self.time = time
		}

		public init() {
			time = Time()
		}
	}
}