import Foundation
import StdMsgs
import RosTime


extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct SingleJointPositionAction: Message {
public static var md5sum: String = "c4a786b7d53e5d0983decf967a5a779e"
public static var datatype = "control_msgs/SingleJointPositionAction"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

SingleJointPositionActionGoal action_goal
SingleJointPositionActionResult action_result
SingleJointPositionActionFeedback action_feedback
"""
public static var hasHeader = false

public var action_goal: SingleJointPositionActionGoal
public var action_result: SingleJointPositionActionResult
public var action_feedback: SingleJointPositionActionFeedback

public init(action_goal: SingleJointPositionActionGoal, action_result: SingleJointPositionActionResult, action_feedback: SingleJointPositionActionFeedback) {
self.action_goal = action_goal
self.action_result = action_result
self.action_feedback = action_feedback
}

public init() {
    action_goal = SingleJointPositionActionGoal()
action_result = SingleJointPositionActionResult()
action_feedback = SingleJointPositionActionFeedback()
}

}
}
