import Foundation
import StdMsgs
import RosTime


extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct SingleJointPositionFeedback: Message {
public static var md5sum: String = "8cee65610a3d08e0a1bded82f146f1fd"
public static var datatype = "control_msgs/SingleJointPositionFeedback"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
Header header
float64 position
float64 velocity
float64 error
"""
public static var hasHeader = false

public var header: std_msgs.header
public var position: Float64
public var velocity: Float64
public var error: Float64

public init(header: std_msgs.header, position: Float64, velocity: Float64, error: Float64) {
self.header = header
self.position = position
self.velocity = velocity
self.error = error
}

public init() {
    header = std_msgs.header()
position = Float64()
velocity = Float64()
error = Float64()
}

}
}
