import Foundation
import StdMsgs
import RosTime
import actionlib_msgs

extension control_msgs {
/// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
public struct SingleJointPositionActionFeedback: Message {
public static var md5sum: String = "3503b7cf8972f90d245850a5d8796cfa"
public static var datatype = "control_msgs/SingleJointPositionActionFeedback"
public static var definition = """
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
SingleJointPositionFeedback feedback
"""
public static var hasHeader = false

public var header: std_msgs.header
public var status: actionlib_msgs.GoalStatus
public var feedback: SingleJointPositionFeedback

public init(header: std_msgs.header, status: actionlib_msgs.GoalStatus, feedback: SingleJointPositionFeedback) {
self.header = header
self.status = status
self.feedback = feedback
}

public init() {
    header = std_msgs.header()
status = actionlib_msgs.GoalStatus()
feedback = SingleJointPositionFeedback()
}

}
}
