// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs
import nav_msgs

extension map_msgs {

	public struct GetMapROIResponse: ServiceMessage {
		public static let md5sum: String = "4d1986519c00d81967d2891a606b234c"
		public static let datatype = "map_msgs/GetMapROIResponse"
		public static var srvMd5sum: String = GetMapROI.md5sum
		public static var srvDatatype: String = GetMapROI.datatype
		public static let definition = """
			nav_msgs/OccupancyGrid sub_map
			"""

	
		public var sub_map: nav_msgs.OccupancyGrid

		public init(sub_map: nav_msgs.OccupancyGrid) {
			self.sub_map = sub_map
		}

		public init() {
			sub_map = nav_msgs.OccupancyGrid()
		}
	}
}