// Generated by msgbuilder 2020-05-10 06:44:10 +0000

import StdMsgs

extension map_msgs {
	public struct GetMapROI: ServiceProt {
		public typealias Request = map_msgs.GetMapROIRequest
		public typealias Response = map_msgs.GetMapROIResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "81aa75ecf00f4571a9be0d9dc6dea512"
		public static let datatype = "map_msgs/GetMapROI"
	}
}