// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension map_msgs {

	public struct GetMapROIRequest: ServiceMessage {
		public static let md5sum: String = "43c2ff8f45af555c0eaf070c401e9a47"
		public static let datatype = "map_msgs/GetMapROIRequest"
		public static var srvMd5sum: String = GetMapROI.md5sum
		public static var srvDatatype: String = GetMapROI.datatype
		public static let definition = """
			float64 x
			float64 y
			float64 l_x
			float64 l_y
			"""

	
		public var x: Float64
		public var y: Float64
		public var l_x: Float64
		public var l_y: Float64

		public init(x: Float64, y: Float64, l_x: Float64, l_y: Float64) {
			self.x = x
			self.y = y
			self.l_x = l_x
			self.l_y = l_y
		}

		public init() {
			x = Float64()
			y = Float64()
			l_x = Float64()
			l_y = Float64()
		}
	}
}