// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs
import sensor_msgs

extension map_msgs {

	public struct GetPointMapResponse: ServiceMessage {
		public static let md5sum: String = "1c9461d0f8a62e03d8b087a3060bd0aa"
		public static let datatype = "map_msgs/GetPointMapResponse"
		public static var srvMd5sum: String = GetPointMap.md5sum
		public static var srvDatatype: String = GetPointMap.datatype
		public static let definition = """
			sensor_msgs/PointCloud2 map
			"""

	
		public var map: sensor_msgs.PointCloud2

		public init(map: sensor_msgs.PointCloud2) {
			self.map = map
		}

		public init() {
			map = sensor_msgs.PointCloud2()
		}
	}
}