// Generated by msgbuilder 2020-05-12 11:56:11 +0000

import StdMsgs

extension map_msgs {
	public struct GetPointMap: ServiceProt {
		public typealias Request = GetPointMapRequest
		public typealias Response = GetPointMapResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "1c9461d0f8a62e03d8b087a3060bd0aa"
		public static let datatype = "map_msgs/GetPointMap"
	}
}