// Generated by msgbuilder 2020-05-12 11:56:11 +0000

import StdMsgs

extension map_msgs {
	public struct GetPointMapROI: ServiceProt {
		public typealias Request = GetPointMapROIRequest
		public typealias Response = GetPointMapROIResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "db7d57ae8b5c7127e46a26389d895b93"
		public static let datatype = "map_msgs/GetPointMapROI"
	}
}