// Generated by msgbuilder 2020-05-15 06:20:49 +0000

import StdMsgs

extension map_msgs {
	public enum GetPointMap: ServiceProt {
		public static let md5sum: String = "1c9461d0f8a62e03d8b087a3060bd0aa"
		public static let datatype = "map_msgs/GetPointMap"

		/// Get the map as a sensor_msgs/PointCloud2 
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
			public static let datatype = "map_msgs/GetPointMapRequest"
			public typealias ServiceType = GetPointMap
			public static let definition = """
				# Get the map as a sensor_msgs/PointCloud2 
				"""
	
			public init() {
		
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "1c9461d0f8a62e03d8b087a3060bd0aa"
			public static let datatype = "map_msgs/GetPointMapResponse"
			public typealias ServiceType = GetPointMap
			public static let definition = "sensor_msgs/PointCloud2 map"
	
			public var map: sensor_msgs.PointCloud2
	
			public init(map: sensor_msgs.PointCloud2) {
				self.map = map
			}
	
			public init() {
				map = sensor_msgs.PointCloud2()
			}
		}

	}
}