// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs
import sensor_msgs

extension map_msgs {

	public struct GetPointMapROIResponse: ServiceMessage {
		public static let md5sum: String = "f4dbcc6a712431af2407eb281c8f0695"
		public static let datatype = "map_msgs/GetPointMapROIResponse"
		public static var srvMd5sum: String = GetPointMapROI.md5sum
		public static var srvDatatype: String = GetPointMapROI.datatype
		public static let definition = """
			sensor_msgs/PointCloud2 sub_map
			"""

	
		public var sub_map: sensor_msgs.PointCloud2

		public init(sub_map: sensor_msgs.PointCloud2) {
			self.sub_map = sub_map
		}

		public init() {
			sub_map = sensor_msgs.PointCloud2()
		}
	}
}