// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

public enum map_msgs {
    public static let all: [String: Message.Type] = [
        "OccupancyGridUpdate": OccupancyGridUpdate.self,
		"PointCloud2Update": PointCloud2Update.self,
		"ProjectedMap": ProjectedMap.self,
		"ProjectedMapInfo": ProjectedMapInfo.self]
}