// Generated by msgbuilder 2020-05-10 10:59:44 +0000

import StdMsgs

public enum map_msgs {
    public static let all: [String: Message.Type] = [
        "PointCloud2Update": PointCloud2Update.self,
		"ProjectedMapInfo": ProjectedMapInfo.self,
		"OccupancyGridUpdate": OccupancyGridUpdate.self,
		"ProjectedMap": ProjectedMap.self]
}