// Generated by msgbuilder 2020-05-05 18:40:13 +0000

import StdMsgs

extension map_msgs {

	public struct OccupancyGridUpdate: MessageWithHeader {
		public static let md5sum: String = "b295be292b335c34718bd939deebe1c9"
		public static let datatype = "map_msgs/OccupancyGridUpdate"
		public static let definition = """
			Header header
			int32 x
			int32 y
			uint32 width
			uint32 height
			int8[] data
			"""

	
		public var header: std_msgs.Header
		public var x: Int32
		public var y: Int32
		public var width: UInt32
		public var height: UInt32
		public var data: [Int8]

		public init(header: std_msgs.Header, x: Int32, y: Int32, width: UInt32, height: UInt32, data: [Int8]) {
			self.header = header
			self.x = x
			self.y = y
			self.width = width
			self.height = height
			self.data = data
		}

		public init() {
			header = std_msgs.Header()
			x = Int32()
			y = Int32()
			width = UInt32()
			height = UInt32()
			data = [Int8]()
		}
	}
}