// Generated by msgbuilder 2020-05-14 06:44:12 +0000

import StdMsgs

extension map_msgs {
	public enum SetMapProjections: ServiceProt {
		public static let md5sum: String = "d7980a33202421c8cd74565e57a4d229"
		public static let datatype = "map_msgs/SetMapProjections"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
			public static let datatype = "map_msgs/SetMapProjectionsRequest"
			public typealias ServiceType = SetMapProjections
			public static let definition = """
				
				"""
	
		
		
	
	
	
			public init() {
		
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "d7980a33202421c8cd74565e57a4d229"
			public static let datatype = "map_msgs/SetMapProjectionsResponse"
			public typealias ServiceType = SetMapProjections
			public static let definition = """
				map_msgs/ProjectedMapInfo[] projected_maps_info
				"""
	
		
			public var projected_maps_info: [ProjectedMapInfo]
	
			public init(projected_maps_info: [ProjectedMapInfo]) {
				self.projected_maps_info = projected_maps_info
			}
	
			public init() {
				projected_maps_info = [ProjectedMapInfo]()
			}
		}

	}
}