// Generated by msgbuilder 2020-05-10 05:59:01 +0000

import StdMsgs

extension map_msgs {
	public struct SetMapProjections: ServiceProt {
		public typealias Request = map_msgs.SetMapProjectionsRequest
		public typealias Response = map_msgs.SetMapProjectionsResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "d7980a33202421c8cd74565e57a4d229"
		public static let datatype = "map_msgs/SetMapProjections"
	}
}