// Generated by msgbuilder 2020-05-10 05:39:47 +0000

import StdMsgs

extension map_msgs {

	public struct SetMapProjectionsRequest: ServiceMessage {
		public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
		public static let datatype = "map_msgs/SetMapProjectionsRequest"
		public static var srvMd5sum: String = SetMapProjections.md5sum
		public static var srvDatatype: String = SetMapProjections.datatype
		public static let definition = """
			
			"""

	
	



		public init() {
	
		}
	}
}