#if !canImport(ObjectiveC)
import XCTest

extension RosmasterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RosmasterTests = [
        ("testChangeSibling", testChangeSibling),
        ("testComputeAllKeys", testComputeAllKeys),
        ("testGetLongName", testGetLongName),
        ("testLongName", testLongName),
        ("testMultiMap", testMultiMap),
        ("testParameters", testParameters),
        ("testParameterServer", testParameterServer),
        ("testResolveNames", testResolveNames),
        ("testUpdates", testUpdates),
        ("testUpdates2", testUpdates2),
        ("testXmlRpcIteration", testXmlRpcIteration),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RosmasterTests.__allTests__RosmasterTests),
    ]
}
#endif
