// Generated by msgbuilder 2020-05-10 09:53:03 +0000

import StdMsgs

extension geographic_msgs {
	/// Geographic map bounding box. 
	///
	/// The two GeoPoints denote diagonally opposite corners of the box.
	///
	/// If min_pt.latitude is NaN, the bounding box is "global", matching
	/// any valid latitude, longitude and altitude.
	///
	/// If min_pt.altitude is NaN, the bounding box is two-dimensional and
	/// matches any altitude within the specified latitude and longitude
	/// range.
	public struct BoundingBox: Message {
		public static let md5sum: String = "f62e8b5e390a3ac7603250d46e8f8446"
		public static let datatype = "geographic_msgs/BoundingBox"
		public static let definition = """
			# Geographic map bounding box. 
			#
			# The two GeoPoints denote diagonally opposite corners of the box.
			#
			# If min_pt.latitude is NaN, the bounding box is "global", matching
			# any valid latitude, longitude and altitude.
			#
			# If min_pt.altitude is NaN, the bounding box is two-dimensional and
			# matches any altitude within the specified latitude and longitude
			# range.
			GeoPoint min_pt         # lowest and most Southwestern corner
			GeoPoint max_pt         # highest and most Northeastern corner
			"""

	
		public var min_pt: GeoPoint
		public var max_pt: GeoPoint

		public init(min_pt: GeoPoint, max_pt: GeoPoint) {
			self.min_pt = min_pt
			self.max_pt = max_pt
		}

		public init() {
			min_pt = GeoPoint()
			max_pt = GeoPoint()
		}
	}
}