// Generated by msgbuilder 2020-05-12 11:59:44 +0000

import StdMsgs

public enum geographic_msgs {
    public static let all: [String: Message.Type] = [
        "BoundingBox": BoundingBox.self,
		"GeoPath": GeoPath.self,
		"GeoPoint": GeoPoint.self,
		"GeoPointStamped": GeoPointStamped.self,
		"GeoPose": GeoPose.self,
		"GeoPoseStamped": GeoPoseStamped.self,
		"GeographicMap": GeographicMap.self,
		"GeographicMapChanges": GeographicMapChanges.self,
		"KeyValue": KeyValue.self,
		"MapFeature": MapFeature.self,
		"RouteNetwork": RouteNetwork.self,
		"RoutePath": RoutePath.self,
		"RouteSegment": RouteSegment.self,
		"WayPoint": WayPoint.self]
}