// Generated by msgbuilder 2020-05-10 09:53:03 +0000

import StdMsgs

extension geographic_msgs {
	/// Geographic map tag (key, value) pair
	///
	/// This is equivalent to diagnostic_msgs/KeyValue, repeated here to
	/// avoid introducing a trivial stack dependency.
	public struct KeyValue: Message {
		public static let md5sum: String = "cf57fdc6617a881a88c16e768132149c"
		public static let datatype = "geographic_msgs/KeyValue"
		public static let definition = """
			# Geographic map tag (key, value) pair
			#
			# This is equivalent to diagnostic_msgs/KeyValue, repeated here to
			# avoid introducing a trivial stack dependency.
			string key                     # tag label
			string value                   # corresponding value
			"""

	
		public var key: String
		public var value: String

		public init(key: String, value: String) {
			self.key = key
			self.value = value
		}

		public init() {
			key = String()
			value = String()
		}
	}
}