// Generated by msgbuilder 2020-05-10 10:00:11 +0000

import StdMsgs

extension geographic_msgs {

	public struct GeoPoseStamped: MessageWithHeader {
		public static let md5sum: String = "cc409c8ed6064d8a846fa207bf3fba6b"
		public static let datatype = "geographic_msgs/GeoPoseStamped"
		public static let definition = """
			Header header
			geographic_msgs/GeoPose pose
			"""

	
		public var header: std_msgs.Header
		public var pose: GeoPose

		public init(header: std_msgs.Header, pose: GeoPose) {
			self.header = header
			self.pose = pose
		}

		public init() {
			header = std_msgs.Header()
			pose = GeoPose()
		}
	}
}