// Generated by msgbuilder 2020-05-12 12:09:05 +0000

import StdMsgs

extension geographic_msgs {
	/// Geographic pose, using the WGS 84 reference ellipsoid.
	///
	/// Orientation uses the East-North-Up (ENU) frame of reference.
	/// (But, what about singularities at the poles?)
	public struct GeoPose: Message {
		public static let md5sum: String = "778680b5172de58b7c057d973576c784"
		public static let datatype = "geographic_msgs/GeoPose"
		public static let definition = """
			# Geographic pose, using the WGS 84 reference ellipsoid.
			#
			# Orientation uses the East-North-Up (ENU) frame of reference.
			# (But, what about singularities at the poles?)
			GeoPoint position
			geometry_msgs/Quaternion orientation
			"""

	
		public var position: GeoPoint
		public var orientation: geometry_msgs.Quaternion

		public init(position: GeoPoint, orientation: geometry_msgs.Quaternion) {
			self.position = position
			self.orientation = orientation
		}

		public init() {
			position = GeoPoint()
			orientation = geometry_msgs.Quaternion()
		}
	}
}