// Generated by msgbuilder 2020-05-10 10:00:10 +0000

import StdMsgs

extension geographic_msgs {

	public struct GeoPath: MessageWithHeader {
		public static let md5sum: String = "1476008e63041203a89257cfad97308f"
		public static let datatype = "geographic_msgs/GeoPath"
		public static let definition = """
			std_msgs/Header header
			geographic_msgs/GeoPoseStamped[] poses
			"""

	
		public var header: std_msgs.Header
		public var poses: [GeoPoseStamped]

		public init(header: std_msgs.Header, poses: [GeoPoseStamped]) {
			self.header = header
			self.poses = poses
		}

		public init() {
			header = std_msgs.Header()
			poses = [GeoPoseStamped]()
		}
	}
}