// Generated by msgbuilder 2020-05-12 12:09:05 +0000

import StdMsgs

extension geographic_msgs {
	public struct GetGeoPath: ServiceProt {
		public typealias Request = GetGeoPathRequest
		public typealias Response = GetGeoPathResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "ee0dbd181711a70f823cc5d415fa609b"
		public static let datatype = "geographic_msgs/GetGeoPath"
	}
}