// Generated by msgbuilder 2020-05-14 06:57:32 +0000

import StdMsgs

extension geographic_msgs {
	public enum GetGeographicMap: ServiceProt {
		public static let md5sum: String = "c0278e653eee0ad79600510650e7be39"
		public static let datatype = "geographic_msgs/GetGeographicMap"

		/// This service requests a region of a geographic map.
		/// Bounding box for the desired map.  If all zeros, provide all data
		/// available from the specified URL.
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "505cc89008cb1745810d2ee4ea646d6e"
			public static let datatype = "geographic_msgs/GetGeographicMapRequest"
			public typealias ServiceType = GetGeographicMap
			public static let definition = """
				# This service requests a region of a geographic map.
				string url            # where to read map data
				# Bounding box for the desired map.  If all zeros, provide all data
				# available from the specified URL.
				BoundingBox bounds
				"""
	
		
			public var url: String
			public var bounds: BoundingBox
	
			public init(url: String, bounds: BoundingBox) {
				self.url = url
				self.bounds = bounds
			}
	
			public init() {
				url = String()
				bounds = BoundingBox()
			}
		}

		/// The requested map, its bounds may differ from the requested bounds.
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "0910332806c65953a4f4252eb780811a"
			public static let datatype = "geographic_msgs/GetGeographicMapResponse"
			public typealias ServiceType = GetGeographicMap
			public static let definition = """
				bool success          # true if the call succeeded
				string status         # more details
				# The requested map, its bounds may differ from the requested bounds.
				GeographicMap map
				"""
	
		
			public var success: Bool
			public var status: String
			public var map: GeographicMap
	
			public init(success: Bool, status: String, map: GeographicMap) {
				self.success = success
				self.status = status
				self.map = map
			}
	
			public init() {
				success = Bool()
				status = String()
				map = GeographicMap()
			}
		}

	}
}