// Generated by msgbuilder 2020-05-10 09:53:03 +0000

import StdMsgs

extension geographic_msgs {
	/// This service requests a region of a geographic map.
	/// Bounding box for the desired map.  If all zeros, provide all data
	/// available from the specified URL.
	public struct GetGeographicMapRequest: ServiceMessage {
		public static let md5sum: String = "505cc89008cb1745810d2ee4ea646d6e"
		public static let datatype = "geographic_msgs/GetGeographicMapRequest"
		public static var srvMd5sum: String = GetGeographicMap.md5sum
		public static var srvDatatype: String = GetGeographicMap.datatype
		public static let definition = """
			# This service requests a region of a geographic map.
			string url            # where to read map data
			# Bounding box for the desired map.  If all zeros, provide all data
			# available from the specified URL.
			BoundingBox bounds
			"""

	
		public var url: String
		public var bounds: BoundingBox

		public init(url: String, bounds: BoundingBox) {
			self.url = url
			self.bounds = bounds
		}

		public init() {
			url = String()
			bounds = BoundingBox()
		}
	}
}