// Generated by msgbuilder 2020-05-10 10:00:10 +0000

import StdMsgs

extension geographic_msgs {
	public struct GetGeographicMap: ServiceProt {
		public typealias Request = geographic_msgs.GetGeographicMapRequest
		public typealias Response = geographic_msgs.GetGeographicMapResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "c0278e653eee0ad79600510650e7be39"
		public static let datatype = "geographic_msgs/GetGeographicMap"
	}
}