// Generated by msgbuilder 2020-05-10 09:53:03 +0000

import StdMsgs

extension geographic_msgs {
	/// Searches for given start and goal the nearest route segments
	/// and determine the path through the RouteNetwork
	public struct GetGeoPathRequest: ServiceMessage {
		public static let md5sum: String = "cad6de11e4ae4ca568785186e1f99f89"
		public static let datatype = "geographic_msgs/GetGeoPathRequest"
		public static var srvMd5sum: String = GetGeoPath.md5sum
		public static var srvDatatype: String = GetGeoPath.datatype
		public static let definition = """
			# Searches for given start and goal the nearest route segments
			# and determine the path through the RouteNetwork
			geographic_msgs/GeoPoint start        # starting point
			geographic_msgs/GeoPoint goal         # goal point
			"""

	
		public var start: GeoPoint
		public var goal: GeoPoint

		public init(start: GeoPoint, goal: GeoPoint) {
			self.start = start
			self.goal = goal
		}

		public init() {
			start = GeoPoint()
			goal = GeoPoint()
		}
	}
}