// Generated by msgbuilder 2020-05-10 10:00:10 +0000

import StdMsgs

extension geographic_msgs {
	public struct GetGeoPath: ServiceProt {
		public typealias Request = geographic_msgs.GetGeoPathRequest
		public typealias Response = geographic_msgs.GetGeoPathResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "ee0dbd181711a70f823cc5d415fa609b"
		public static let datatype = "geographic_msgs/GetGeoPath"
	}
}