// Generated by msgbuilder 2020-05-10 10:00:10 +0000

import StdMsgs

extension geographic_msgs {
	/// Get a plan to traverse a route network from start to goal.
	///
	/// Similar to nav_msgs/GetPlan, but constrained to use the route network.
	public struct GetRoutePlanRequest: ServiceMessage {
		public static let md5sum: String = "e56ac34268c6d575dabb30f42da4a47a"
		public static let datatype = "geographic_msgs/GetRoutePlanRequest"
		public static var srvMd5sum: String = GetRoutePlan.md5sum
		public static var srvDatatype: String = GetRoutePlan.datatype
		public static let definition = """
			# Get a plan to traverse a route network from start to goal.
			#
			# Similar to nav_msgs/GetPlan, but constrained to use the route network.
			uuid_msgs/UniqueID network      # route network to use
			uuid_msgs/UniqueID start        # starting way point
			uuid_msgs/UniqueID goal         # goal way point
			"""

	
		public var network: uuid_msgs.UniqueID
		public var start: uuid_msgs.UniqueID
		public var goal: uuid_msgs.UniqueID

		public init(network: uuid_msgs.UniqueID, start: uuid_msgs.UniqueID, goal: uuid_msgs.UniqueID) {
			self.network = network
			self.start = start
			self.goal = goal
		}

		public init() {
			network = uuid_msgs.UniqueID()
			start = uuid_msgs.UniqueID()
			goal = uuid_msgs.UniqueID()
		}
	}
}
