// Generated by msgbuilder 2020-05-10 10:00:10 +0000

import StdMsgs

extension geographic_msgs {
	public struct GetRoutePlan: ServiceProt {
		public typealias Request = geographic_msgs.GetRoutePlanRequest
		public typealias Response = geographic_msgs.GetRoutePlanResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "04479050c4f2a58d915ceec419e70b4e"
		public static let datatype = "geographic_msgs/GetRoutePlan"
	}
}