// Generated by msgbuilder 2020-05-10 10:00:10 +0000

import StdMsgs

extension geographic_msgs {

	public struct GetRoutePlanResponse: ServiceMessage {
		public static let md5sum: String = "28ee54f0ccb2ab28b46048ebc6fa5aff"
		public static let datatype = "geographic_msgs/GetRoutePlanResponse"
		public static var srvMd5sum: String = GetRoutePlan.md5sum
		public static var srvDatatype: String = GetRoutePlan.datatype
		public static let definition = """
			bool            success         # true if the call succeeded
			string          status          # more details
			RoutePath       plan            # path to follow
			"""

	
		public var success: Bool
		public var status: String
		public var plan: RoutePath

		public init(success: Bool, status: String, plan: RoutePath) {
			self.success = success
			self.status = status
			self.plan = plan
		}

		public init() {
			success = Bool()
			status = String()
			plan = RoutePath()
		}
	}
}