// Generated by msgbuilder 2020-05-12 12:09:05 +0000

import StdMsgs

extension geographic_msgs {
	public struct GetRoutePlan: ServiceProt {
		public typealias Request = GetRoutePlanRequest
		public typealias Response = GetRoutePlanResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "04479050c4f2a58d915ceec419e70b4e"
		public static let datatype = "geographic_msgs/GetRoutePlan"
	}
}