// Generated by msgbuilder 2020-05-10 10:00:10 +0000

import StdMsgs


extension geographic_msgs {
	/// Geographic map feature.
	///
	/// A list of WayPoint IDs for features like streets, highways, hiking
	/// trails, the outlines of buildings and parking lots in sequential
	/// order.
	///
	/// Feature lists may also contain other feature lists as members.
	public struct MapFeature: Message {
		public static let md5sum: String = "e2505ace5e8da8a15b610eaf62bdefae"
		public static let datatype = "geographic_msgs/MapFeature"
		public static let definition = """
			# Geographic map feature.
			#
			# A list of WayPoint IDs for features like streets, highways, hiking
			# trails, the outlines of buildings and parking lots in sequential
			# order.
			#
			# Feature lists may also contain other feature lists as members.
			uuid_msgs/UniqueID   id         # Unique feature identifier
			uuid_msgs/UniqueID[] components # Sequence of feature components
			KeyValue[] props                # Key/value properties for this feature
			"""

	
		public var id: uuid_msgs.UniqueID
		public var components: [uuid_msgs.UniqueID]
		public var props: [KeyValue]

		public init(id: uuid_msgs.UniqueID, components: [uuid_msgs.UniqueID], props: [KeyValue]) {
			self.id = id
			self.components = components
			self.props = props
		}

		public init() {
			id = uuid_msgs.UniqueID()
			components = [uuid_msgs.UniqueID]()
			props = [KeyValue]()
		}
	}
}
