// Generated by msgbuilder 2020-05-12 12:09:05 +0000

import StdMsgs

extension geographic_msgs {
	/// Geographic map route network.
	///
	/// A directed graph of WayPoint nodes and RouteSegment edges.  This
	/// information is extracted from the more-detailed contents of a
	/// GeographicMap.  A RouteNetwork contains only the way points and
	/// route segments of interest for path planning.
	public struct RouteNetwork: MessageWithHeader {
		public static let md5sum: String = "fd717c0a34a7c954deed32c6847f30a8"
		public static let datatype = "geographic_msgs/RouteNetwork"
		public static let definition = """
			# Geographic map route network.
			#
			# A directed graph of WayPoint nodes and RouteSegment edges.  This
			# information is extracted from the more-detailed contents of a
			# GeographicMap.  A RouteNetwork contains only the way points and
			# route segments of interest for path planning.
			Header          header
			uuid_msgs/UniqueID id    # This route network identifier
			BoundingBox     bounds   # 2D bounding box for network
			WayPoint[]      points   # Way points in this network
			RouteSegment[]  segments # Directed edges of this network
			KeyValue[]      props    # Network key/value properties
			"""

	
		public var header: std_msgs.Header
		public var id: uuid_msgs.UniqueID
		public var bounds: BoundingBox
		public var points: [WayPoint]
		public var segments: [RouteSegment]
		public var props: [KeyValue]

		public init(header: std_msgs.Header, id: uuid_msgs.UniqueID, bounds: BoundingBox, points: [WayPoint], segments: [RouteSegment], props: [KeyValue]) {
			self.header = header
			self.id = id
			self.bounds = bounds
			self.points = points
			self.segments = segments
			self.props = props
		}

		public init() {
			header = std_msgs.Header()
			id = uuid_msgs.UniqueID()
			bounds = BoundingBox()
			points = [WayPoint]()
			segments = [RouteSegment]()
			props = [KeyValue]()
		}
	}
}