// Generated by msgbuilder 2020-05-10 10:00:10 +0000

import StdMsgs


extension geographic_msgs {
	/// Path through a route network.
	///
	/// A path is a sequence of RouteSegment edges.  This information is
	/// extracted from a RouteNetwork graph.  A RoutePath lists the route
	/// segments needed to reach some chosen goal.
	public struct RoutePath: MessageWithHeader {
		public static let md5sum: String = "0aa2dd809a8091bdb4466dfefecbb8cf"
		public static let datatype = "geographic_msgs/RoutePath"
		public static let definition = """
			# Path through a route network.
			#
			# A path is a sequence of RouteSegment edges.  This information is
			# extracted from a RouteNetwork graph.  A RoutePath lists the route
			# segments needed to reach some chosen goal.
			Header header
			uuid_msgs/UniqueID   network    # Route network containing this path
			uuid_msgs/UniqueID[] segments   # Sequence of RouteSegment IDs
			KeyValue[]           props      # Key/value properties
			"""

	
		public var header: std_msgs.Header
		public var network: uuid_msgs.UniqueID
		public var segments: [uuid_msgs.UniqueID]
		public var props: [KeyValue]

		public init(header: std_msgs.Header, network: uuid_msgs.UniqueID, segments: [uuid_msgs.UniqueID], props: [KeyValue]) {
			self.header = header
			self.network = network
			self.segments = segments
			self.props = props
		}

		public init() {
			header = std_msgs.Header()
			network = uuid_msgs.UniqueID()
			segments = [uuid_msgs.UniqueID]()
			props = [KeyValue]()
		}
	}
}
