// Generated by msgbuilder 2020-05-10 10:00:10 +0000

import StdMsgs

extension geographic_msgs {
	public struct UpdateGeographicMap: ServiceProt {
		public typealias Request = geographic_msgs.UpdateGeographicMapRequest
		public typealias Response = geographic_msgs.UpdateGeographicMapResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "93db3f1ec099e9f1b7e442d7d397e244"
		public static let datatype = "geographic_msgs/UpdateGeographicMap"
	}
}