// Generated by msgbuilder 2020-05-12 12:09:05 +0000

import StdMsgs

extension geographic_msgs {
	public struct UpdateGeographicMap: ServiceProt {
		public typealias Request = UpdateGeographicMapRequest
		public typealias Response = UpdateGeographicMapResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "93db3f1ec099e9f1b7e442d7d397e244"
		public static let datatype = "geographic_msgs/UpdateGeographicMap"
	}
}