// Generated by msgbuilder 2020-05-10 09:53:03 +0000

import StdMsgs

extension geographic_msgs {

	public struct UpdateGeographicMapResponse: ServiceMessage {
		public static let md5sum: String = "38b8954d32a849f31d78416b12bff5d1"
		public static let datatype = "geographic_msgs/UpdateGeographicMapResponse"
		public static var srvMd5sum: String = UpdateGeographicMap.md5sum
		public static var srvDatatype: String = UpdateGeographicMap.datatype
		public static let definition = """
			bool   success        # true if the call succeeded
			string status         # more details
			"""

	
		public var success: Bool
		public var status: String

		public init(success: Bool, status: String) {
			self.success = success
			self.status = status
		}

		public init() {
			success = Bool()
			status = String()
		}
	}
}