// Generated by msgbuilder 2020-05-10 10:00:10 +0000

import StdMsgs

extension geographic_msgs {
	/// This service updates a geographic map.
	/// Changes to geographic map.
	public struct UpdateGeographicMapRequest: ServiceMessage {
		public static let md5sum: String = "8d8da723a1fadc5f7621a18b4e72fc3b"
		public static let datatype = "geographic_msgs/UpdateGeographicMapRequest"
		public static var srvMd5sum: String = UpdateGeographicMap.md5sum
		public static var srvDatatype: String = UpdateGeographicMap.datatype
		public static let definition = """
			# This service updates a geographic map.
			# Changes to geographic map.
			GeographicMapChanges updates
			"""

	
		public var updates: GeographicMapChanges

		public init(updates: GeographicMapChanges) {
			self.updates = updates
		}

		public init() {
			updates = GeographicMapChanges()
		}
	}
}