// Generated by msgbuilder 2020-05-12 12:09:05 +0000

import StdMsgs

extension geographic_msgs {
	/// Way-point element for a geographic map.
	public struct WayPoint: Message {
		public static let md5sum: String = "ef04f823aef332455a49eaec3f1761b7"
		public static let datatype = "geographic_msgs/WayPoint"
		public static let definition = """
			# Way-point element for a geographic map.
			uuid_msgs/UniqueID id   # Unique way-point identifier
			GeoPoint   position     # Position relative to WGS 84 ellipsoid
			KeyValue[] props        # Key/value properties for this point
			"""

	
		public var id: uuid_msgs.UniqueID
		public var position: GeoPoint
		public var props: [KeyValue]

		public init(id: uuid_msgs.UniqueID, position: GeoPoint, props: [KeyValue]) {
			self.id = id
			self.position = position
			self.props = props
		}

		public init() {
			id = uuid_msgs.UniqueID()
			position = GeoPoint()
			props = [KeyValue]()
		}
	}
}