// Generated by msgbuilder 2020-04-29 05:17:11 +0000

import StdMsgs

extension pcl_msgs {

	public struct ModelCoefficients: MessageWithHeader {
		public static let md5sum: String = "ca27dea75e72cb894cd36f9e5005e93e"
		public static let datatype = "pcl_msgs/ModelCoefficients"
		public static let definition = """
			Header header
			float32[] values
			"""

		public static let hasHeader = true

	
		public var header: std_msgs.Header
		public var values: [Float32]

		public init(header: std_msgs.Header, values: [Float32]) {
			self.header = header
			self.values = values
		}

		public init() {
			header = std_msgs.Header()
			values = [Float32]()
		}
	}
}