// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

public enum pcl_msgs {
    public static let all: [String: Message.Type] = [
        "ModelCoefficients": ModelCoefficients.self,
		"PointIndices": PointIndices.self,
		"PolygonMesh": PolygonMesh.self,
		"Vertices": Vertices.self]
}