// Generated by msgbuilder 2020-05-10 10:59:44 +0000

import StdMsgs

public enum pcl_msgs {
    public static let all: [String: Message.Type] = [
        "ModelCoefficients": ModelCoefficients.self,
		"PointIndices": PointIndices.self,
		"Vertices": Vertices.self,
		"PolygonMesh": PolygonMesh.self]
}