// Generated by msgbuilder 2020-04-29 05:17:11 +0000

import StdMsgs

extension pcl_msgs {

	public struct PointIndices: MessageWithHeader {
		public static let md5sum: String = "458c7998b7eaf99908256472e273b3d4"
		public static let datatype = "pcl_msgs/PointIndices"
		public static let definition = """
			Header header
			int32[] indices
			"""

		public static let hasHeader = true

	
		public var header: std_msgs.Header
		public var indices: [Int32]

		public init(header: std_msgs.Header, indices: [Int32]) {
			self.header = header
			self.indices = indices
		}

		public init() {
			header = std_msgs.Header()
			indices = [Int32]()
		}
	}
}