// Generated by msgbuilder 2019-05-02 08:13:20 +0000



extension std_msgs {
	public struct bool: Message {
		public static let md5sum: String = "8b94c1b53db61fb6aed406028ad6332a"
		public static let datatype = "std_msgs/Bool"
		public static let definition = "bool data"
		public static let hasHeader = false

		public var data: Bool

		public init(_ value: Bool) {
			self.data = value
		}
	}
}