// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	public struct byte: Message {
		public static let md5sum: String = "ad736a2e8818154c487bb80fe42ce43b"
		public static let datatype = "std_msgs/Byte"
		public static let definition = "byte data"
		public static let hasHeader = false

		public var data: Int8

		public init(_ value: Int8) {
			self.data = value
		}
	}
}