// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	public struct char: Message {
		public static let md5sum: String = "1bf77f25acecdedba0e224b162199717"
		public static let datatype = "std_msgs/Char"
		public static let definition = "char data"
		public static let hasHeader = false

		public var data: UInt8

		public init(_ value: UInt8) {
			self.data = value
		}
	}
}