// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {

	public struct Empty: Message {
		public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
		public static let datatype = "std_msgs/Empty"
		public static let definition = """
			
			"""

		public static let hasHeader = false

	
	



		public init() {
	
		}
	}
}