// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	public struct float64: Message {
		public static let md5sum: String = "fdb28210bfa9d7c91146260178d9a584"
		public static let datatype = "std_msgs/Float64"
		public static let definition = "float64 data"
		public static let hasHeader = false

		public var data: Float64

		public init(_ value: Float64) {
			self.data = value
		}
	}
}