// Generated by msgbuilder 2019-05-02 08:13:23 +0000



extension std_msgs {
	/// Please look at the MultiArrayLayout message definition for
	/// documentation on all multiarrays.
	public struct Float64MultiArray: Message {
		public static let md5sum: String = "4b7d974086d4060e7db4613a7e6c3ba4"
		public static let datatype = "std_msgs/Float64MultiArray"
		public static let definition = """
			# Please look at the MultiArrayLayout message definition for
			# documentation on all multiarrays.
			MultiArrayLayout  layout        # specification of data layout
			float64[]         data          # array of data
			"""

		public static let hasHeader = false

	
		public var layout: MultiArrayLayout
		public var data: [Float64]

		public init(layout: MultiArrayLayout, data: [Float64]) {
			self.layout = layout
			self.data = data
		}

		public init() {
			layout = MultiArrayLayout()
			data = [Float64]()
		}
	}
}