// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	public struct float32: Message {
		public static let md5sum: String = "73fcbf46b49191e672908e50842a83d4"
		public static let datatype = "std_msgs/Float32"
		public static let definition = "float32 data"
		public static let hasHeader = false

		public var data: Float32

		public init(_ value: Float32) {
			self.data = value
		}
	}
}