// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	/// Please look at the MultiArrayLayout message definition for
	/// documentation on all multiarrays.
	public struct Int16MultiArray: Message {
		public static let md5sum: String = "d9338d7f523fcb692fae9d0a0e9f067c"
		public static let datatype = "std_msgs/Int16MultiArray"
		public static let definition = """
			# Please look at the MultiArrayLayout message definition for
			# documentation on all multiarrays.
			MultiArrayLayout  layout        # specification of data layout
			int16[]           data          # array of data
			"""

		public static let hasHeader = false

	
		public var layout: MultiArrayLayout
		public var data: [Int16]

		public init(layout: MultiArrayLayout, data: [Int16]) {
			self.layout = layout
			self.data = data
		}

		public init() {
			layout = MultiArrayLayout()
			data = [Int16]()
		}
	}
}