// Generated by msgbuilder 2019-05-02 08:13:23 +0000



extension std_msgs {
	public struct int32: Message {
		public static let md5sum: String = "da5909fbe378aeaf85e547e830cc1bb7"
		public static let datatype = "std_msgs/Int32"
		public static let definition = "int32 data"
		public static let hasHeader = false

		public var data: Int32

		public init(_ value: Int32) {
			self.data = value
		}
	}
}