// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	/// Please look at the MultiArrayLayout message definition for
	/// documentation on all multiarrays.
	public struct Int32MultiArray: Message {
		public static let md5sum: String = "1d99f79f8b325b44fee908053e9c945b"
		public static let datatype = "std_msgs/Int32MultiArray"
		public static let definition = """
			# Please look at the MultiArrayLayout message definition for
			# documentation on all multiarrays.
			MultiArrayLayout  layout        # specification of data layout
			int32[]           data          # array of data
			"""

		public static let hasHeader = false

	
		public var layout: MultiArrayLayout
		public var data: [Int32]

		public init(layout: MultiArrayLayout, data: [Int32]) {
			self.layout = layout
			self.data = data
		}

		public init() {
			layout = MultiArrayLayout()
			data = [Int32]()
		}
	}
}