// Generated by msgbuilder 2019-05-02 08:13:23 +0000



extension std_msgs {
	/// Please look at the MultiArrayLayout message definition for
	/// documentation on all multiarrays.
	public struct Int64MultiArray: Message {
		public static let md5sum: String = "54865aa6c65be0448113a2afc6a49270"
		public static let datatype = "std_msgs/Int64MultiArray"
		public static let definition = """
			# Please look at the MultiArrayLayout message definition for
			# documentation on all multiarrays.
			MultiArrayLayout  layout        # specification of data layout
			int64[]           data          # array of data
			"""

		public static let hasHeader = false

	
		public var layout: MultiArrayLayout
		public var data: [Int64]

		public init(layout: MultiArrayLayout, data: [Int64]) {
			self.layout = layout
			self.data = data
		}

		public init() {
			layout = MultiArrayLayout()
			data = [Int64]()
		}
	}
}