// Generated by msgbuilder 2019-05-02 08:13:22 +0000



extension std_msgs {
	/// Please look at the MultiArrayLayout message definition for
	/// documentation on all multiarrays.
	public struct Int8MultiArray: Message {
		public static let md5sum: String = "d7c1af35a1b4781bbe79e03dd94b7c13"
		public static let datatype = "std_msgs/Int8MultiArray"
		public static let definition = """
			# Please look at the MultiArrayLayout message definition for
			# documentation on all multiarrays.
			MultiArrayLayout  layout        # specification of data layout
			int8[]            data          # array of data
			"""

		public static let hasHeader = false

	
		public var layout: MultiArrayLayout
		public var data: [Int8]

		public init(layout: MultiArrayLayout, data: [Int8]) {
			self.layout = layout
			self.data = data
		}

		public init() {
			layout = MultiArrayLayout()
			data = [Int8]()
		}
	}
}