// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {

	public struct MultiArrayDimension: Message {
		public static let md5sum: String = "4cd0c83a8683deae40ecdac60e53bfa8"
		public static let datatype = "std_msgs/MultiArrayDimension"
		public static let definition = """
			string label   # label of given dimension
			uint32 size    # size of given dimension (in type units)
			uint32 stride  # stride of given dimension
			"""

		public static let hasHeader = false

	
		public var label: String
		public var size: UInt32
		public var stride: UInt32

		public init(label: String, size: UInt32, stride: UInt32) {
			self.label = label
			self.size = size
			self.stride = stride
		}

		public init() {
			label = String()
			size = UInt32()
			stride = UInt32()
		}
	}
}