// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	public struct string: Message {
		public static let md5sum: String = "992ce8a1687cec8c8bd883ec73ca41d1"
		public static let datatype = "std_msgs/String"
		public static let definition = "string data"
		public static let hasHeader = false

		public var data: String

		public init(_ value: String) {
			self.data = value
		}
	}
}