// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	public struct uint64: Message {
		public static let md5sum: String = "1b2a79973e8bf53d7b53acb71299cb57"
		public static let datatype = "std_msgs/UInt64"
		public static let definition = "uint64 data"
		public static let hasHeader = false

		public var data: UInt64

		public init(_ value: UInt64) {
			self.data = value
		}
	}
}