// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	/// Please look at the MultiArrayLayout message definition for
	/// documentation on all multiarrays.
	public struct UInt64MultiArray: Message {
		public static let md5sum: String = "6088f127afb1d6c72927aa1247e945af"
		public static let datatype = "std_msgs/UInt64MultiArray"
		public static let definition = """
			# Please look at the MultiArrayLayout message definition for
			# documentation on all multiarrays.
			MultiArrayLayout  layout        # specification of data layout
			uint64[]          data          # array of data
			"""

		public static let hasHeader = false

	
		public var layout: MultiArrayLayout
		public var data: [UInt64]

		public init(layout: MultiArrayLayout, data: [UInt64]) {
			self.layout = layout
			self.data = data
		}

		public init() {
			layout = MultiArrayLayout()
			data = [UInt64]()
		}
	}
}