// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	/// Please look at the MultiArrayLayout message definition for
	/// documentation on all multiarrays.
	public struct UInt32MultiArray: Message {
		public static let md5sum: String = "4d6a180abc9be191b96a7eda6c8a233d"
		public static let datatype = "std_msgs/UInt32MultiArray"
		public static let definition = """
			# Please look at the MultiArrayLayout message definition for
			# documentation on all multiarrays.
			MultiArrayLayout  layout        # specification of data layout
			uint32[]          data          # array of data
			"""

		public static let hasHeader = false

	
		public var layout: MultiArrayLayout
		public var data: [UInt32]

		public init(layout: MultiArrayLayout, data: [UInt32]) {
			self.layout = layout
			self.data = data
		}

		public init() {
			layout = MultiArrayLayout()
			data = [UInt32]()
		}
	}
}