// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	public struct uint32: Message {
		public static let md5sum: String = "304a39449588c7f8ce2df6e8001c5fce"
		public static let datatype = "std_msgs/UInt32"
		public static let definition = "uint32 data"
		public static let hasHeader = false

		public var data: UInt32

		public init(_ value: UInt32) {
			self.data = value
		}
	}
}