// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	public struct uint8: Message {
		public static let md5sum: String = "7c8164229e7d2c17eb95e9231617fdee"
		public static let datatype = "std_msgs/UInt8"
		public static let definition = "uint8 data"
		public static let hasHeader = false

		public var data: UInt8

		public init(_ value: UInt8) {
			self.data = value
		}
	}
}