// Generated by msgbuilder 2019-05-02 08:13:26 +0000



extension std_msgs {
	/// Please look at the MultiArrayLayout message definition for
	/// documentation on all multiarrays.
	public struct UInt16MultiArray: Message {
		public static let md5sum: String = "52f264f1c973c4b73790d384c6cb4484"
		public static let datatype = "std_msgs/UInt16MultiArray"
		public static let definition = """
			# Please look at the MultiArrayLayout message definition for
			# documentation on all multiarrays.
			MultiArrayLayout  layout        # specification of data layout
			uint16[]            data        # array of data
			"""

		public static let hasHeader = false

	
		public var layout: MultiArrayLayout
		public var data: [UInt16]

		public init(layout: MultiArrayLayout, data: [UInt16]) {
			self.layout = layout
			self.data = data
		}

		public init() {
			layout = MultiArrayLayout()
			data = [UInt16]()
		}
	}
}