// Generated by msgbuilder 2020-05-10 09:54:37 +0000

import StdMsgs

extension uuid_msgs {
	/// A universally unique identifier (UUID).
	///
	///  http://en.wikipedia.org/wiki/Universally_unique_identifier
	///  http://tools.ietf.org/html/rfc4122.html
	public struct UniqueID: Message {
		public static let md5sum: String = "fec2a93b6f5367ee8112c9c0b41ff310"
		public static let datatype = "uuid_msgs/UniqueID"
		public static let definition = """
			# A universally unique identifier (UUID).
			#
			#  http://en.wikipedia.org/wiki/Universally_unique_identifier
			#  http://tools.ietf.org/html/rfc4122.html
			uint8[16] uuid
			"""

	
		public var uuid: FixedLengthUInt8Array16

		public init(uuid: [UInt8]) {
			self.uuid = FixedLengthUInt8Array16(uuid)
		}

		public init() {
			uuid = FixedLengthUInt8Array16()
		}
	}
}