// Generated by msgbuilder 2020-05-12 11:14:36 +0000

import StdMsgs

extension std_srvs {

	public struct EmptyResponse: ServiceMessage {
		public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
		public static let datatype = "std_srvs/EmptyResponse"
		public static var srvMd5sum: String = Empty.md5sum
		public static var srvDatatype: String = Empty.datatype
		public static let definition = """
			
			"""

	
	



		public init() {
	
		}
	}
}