// Generated by msgbuilder 2020-05-12 11:14:36 +0000

import StdMsgs

extension std_srvs {
	public struct Empty: ServiceProt {
		public typealias Request = EmptyRequest
		public typealias Response = EmptyResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
		public static let datatype = "std_srvs/Empty"
	}
}