// Generated by msgbuilder 2020-05-14 06:44:12 +0000

import StdMsgs

extension std_srvs {
	public enum Empty: ServiceProt {
		public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
		public static let datatype = "std_srvs/Empty"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
			public static let datatype = "std_srvs/EmptyRequest"
			public typealias ServiceType = Empty
			public static let definition = """
				---
				"""
	
		
		
	
	
	
			public init() {
		
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
			public static let datatype = "std_srvs/EmptyResponse"
			public typealias ServiceType = Empty
			public static let definition = """
				
				"""
	
		
		
	
	
	
			public init() {
		
			}
		}

	}
}