// Generated by msgbuilder 2020-05-12 11:14:36 +0000

import StdMsgs

extension std_srvs {

	public struct SetBoolResponse: ServiceMessage {
		public static let md5sum: String = "937c9679a518e3a18d831e57125ea522"
		public static let datatype = "std_srvs/SetBoolResponse"
		public static var srvMd5sum: String = SetBool.md5sum
		public static var srvDatatype: String = SetBool.datatype
		public static let definition = """
			bool success   # indicate successful run of triggered service
			string message # informational, e.g. for error messages
			"""

	
		public var success: Bool
		public var message: String

		public init(success: Bool, message: String) {
			self.success = success
			self.message = message
		}

		public init() {
			success = Bool()
			message = String()
		}
	}
}