// Generated by msgbuilder 2020-05-15 06:20:49 +0000

import StdMsgs

extension std_srvs {
	public enum SetBool: ServiceProt {
		public static let md5sum: String = "09fb03525b03e7ea1fd3992bafd87e16"
		public static let datatype = "std_srvs/SetBool"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "8b94c1b53db61fb6aed406028ad6332a"
			public static let datatype = "std_srvs/SetBoolRequest"
			public typealias ServiceType = SetBool
			public static let definition = """
				bool data # e.g. for hardware enabling / disabling
				"""
	
			public var data: Bool
	
			public init(data: Bool) {
				self.data = data
			}
	
			public init() {
				data = Bool()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "937c9679a518e3a18d831e57125ea522"
			public static let datatype = "std_srvs/SetBoolResponse"
			public typealias ServiceType = SetBool
			public static let definition = """
				bool success   # indicate successful run of triggered service
				string message # informational, e.g. for error messages
				"""
	
			public var success: Bool
			public var message: String
	
			public init(success: Bool, message: String) {
				self.success = success
				self.message = message
			}
	
			public init() {
				success = Bool()
				message = String()
			}
		}

	}
}