// Generated by msgbuilder 2020-05-12 11:04:15 +0000

import StdMsgs

extension std_srvs {
	public struct SetBool: ServiceProt {
		public typealias Request = SetBoolRequest
		public typealias Response = SetBoolResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "09fb03525b03e7ea1fd3992bafd87e16"
		public static let datatype = "std_srvs/SetBool"
	}
}