// Generated by msgbuilder 2020-05-12 11:14:36 +0000

import StdMsgs

extension std_srvs {

	public struct TriggerRequest: ServiceMessage {
		public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
		public static let datatype = "std_srvs/TriggerRequest"
		public static var srvMd5sum: String = Trigger.md5sum
		public static var srvDatatype: String = Trigger.datatype
		public static let definition = """
			
			"""

	
	



		public init() {
	
		}
	}
}