// Generated by msgbuilder 2020-05-12 11:04:15 +0000

import StdMsgs

extension std_srvs {
	public struct Trigger: ServiceProt {
		public typealias Request = TriggerRequest
		public typealias Response = TriggerResponse
		public var request: Request
		public var response: Response

		public static let md5sum: String = "937c9679a518e3a18d831e57125ea522"
		public static let datatype = "std_srvs/Trigger"
	}
}