// Generated by msgbuilder 2020-05-05 18:40:13 +0000

import StdMsgs

extension shape_msgs {
	/// Definition of a triangle's vertices
	public struct MeshTriangle: Message {
		public static let md5sum: String = "23688b2e6d2de3d32fe8af104a903253"
		public static let datatype = "shape_msgs/MeshTriangle"
		public static let definition = """
			# Definition of a triangle's vertices
			uint32[3] vertex_indices
			"""

	
		public var vertex_indices: FixedLengthUInt32Array3

		public init(vertex_indices: [UInt32]) {
			self.vertex_indices = FixedLengthUInt32Array3(vertex_indices)
		}

		public init() {
			vertex_indices = FixedLengthUInt32Array3()
		}
	}
}