// Generated by msgbuilder 2020-04-28 15:10:00 +0000

import StdMsgs

extension shape_msgs {
	/// Definition of a triangle's vertices
	public struct MeshTriangle: Message {
		public static let md5sum: String = "23688b2e6d2de3d32fe8af104a903253"
		public static let datatype = "shape_msgs/MeshTriangle"
		public static let definition = """
			# Definition of a triangle's vertices
			uint32[3] vertex_indices
			"""

		public static let hasHeader = false

	
		public var vertex_indices: FixedLengthArray<UInt32>

		public init(vertex_indices: [UInt32]) {
			self.vertex_indices = FixedLengthArray(length: 3, array: vertex_indices)
		}

		public init() {
			vertex_indices = FixedLengthArray(length: 3, array: [UInt32](repeating: 0, count: 3))
		}
	}
}