// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

public enum shape_msgs {
    public static let all: [String: Message.Type] = [
        "Mesh": Mesh.self,
		"MeshTriangle": MeshTriangle.self,
		"Plane": Plane.self,
		"SolidPrimitive": SolidPrimitive.self]
}