// Generated by msgbuilder 2020-05-10 10:59:44 +0000

import StdMsgs

public enum shape_msgs {
    public static let all: [String: Message.Type] = [
        "MeshTriangle": MeshTriangle.self,
		"Plane": Plane.self,
		"Mesh": Mesh.self,
		"SolidPrimitive": SolidPrimitive.self]
}