// Generated by msgbuilder 2020-05-10 10:56:43 +0000

import StdMsgs

public enum actionlib_msgs {
    public static let all: [String: Message.Type] = [
        "GoalStatus": GoalStatus.self,
		"GoalID": GoalID.self,
		"GoalStatusArray": GoalStatusArray.self]
}