// Generated by msgbuilder 2020-05-12 11:56:10 +0000

import StdMsgs

public enum actionlib_msgs {
    public static let all: [String: Message.Type] = [
        "GoalID": GoalID.self,
		"GoalStatus": GoalStatus.self,
		"GoalStatusArray": GoalStatusArray.self]
}